#+Title: PATTERNS OF PATTERNS
# #+AUTHOR: Ligne Étale
# #+Date: June 14th 2021
#+CATEGORY: ERG
#+OPTIONS: toc:nil author:nil date:nil title:nil H:4
#+LATEX_ENGINE: xelatex
#+BIBLIOGRAPHY: /home/joe/PatternsOfPatterns/main.bib
#+HTML_HEAD: <script src="https://hypothes.is/embed.js" async></script>
#+LATEX_CLASS: acmart
#+LATEX_CLASS_OPTIONS: [acmlarge,timestamp,letter]
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \usepackage{afterpage}
#+LATEX_HEADER: \usepackage[pagewise]{lineno}
#+LATEX_HEADER: \renewcommand\thelinenumber{\color{red}\arabic{linenumber}}
# #+LATEX_HEADER: \linenumbers
#+LATEX_HEADER: \usepackage{xunicode}
#+LATEX_HEADER: \usepackage{xelatexemoji}
#+LATEX_HEADER: \renewcommand{\xelatexemojipath}[1]{./svg/U#1.PDF}
#+LATEX_HEADER: \usepackage[no-sscript]{xltxtra}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{xypic}
#+LATEX_HEADER: \usepackage{amsmath, amssymb}
#+LATEX_HEADER: \def\t{\scriptstyle\triangle}
#+LATEX_HEADER: \def\T{\textstyle\blacktriangle}
#+LATEX_HEADER: \usepackage{placeins}
#+LATEX_HEADER: \usepackage{starfont}
#+LATEX_HEADER: \newfontfamily{\alch}{Alchemy}
#+LATEX_HEADER: \newfontfamily\emoji{DejaVu Sans}
#+LATEX_HEADER: \newcommand{\Asclepius}{{\emoji\symbol{"2695}}}
#+LATEX_HEADER: \newcommand{\Caduceus}{{\emoji\symbol{"2624}}}
#+LATEX_HEADER: \setmainfont{Libertinus Sans}
#+LATEX_HEADER: \newenvironment{echo}{}{}
#+LATEX_HEADER: \usepackage{enotez}
#+LATEX_HEADER: \renewcommand{\endnote}[1]{}
#+LATEX_HEADER: \newcommand{\markbf}[1]{\textsuperscript{\textbf{#1}}}
#+LATEX_HEADER: \setenotez{counter-format = alph, mark-cs = \markbf}
#+LATEX_HEADER: \DeclareInstance{enotez-list}{sverre}{paragraph}{heading={},notes-sep=\baselineskip,format=\normalsize\normalfont\raggedright\leftskip1.8em,number=\makebox[0pt][r]{#1.\ }\ignorespaces,}

# #+LATEX_HEADER: \makeatletter\renewcommand*\makeenmark{\hbox{\textsuperscript{\@Alph{\theenmark}}}}\makeatother
# #+LATEX_HEADER: \renewcommand{\notesname}{\vspace{-1\baselineskip}}
# #+LATEX_HEADER: \usepackage{xpatch}
# #+LATEX_HEADER: \makeatletter\xpretocmd{\theendnotes}{\xpatchcmd{\@makeenmark}{\hbox{\@textsuperscript{\normalfont\@theenmark}}}{\hbox{\normalfont\theenmark.\space}}{}{}}{}{}\makeatother

# #+LATEX_HEADER: \RequirePackage[table]{xcolor}
# #+LATEX_HEADER: \DeclareHookRule{begindocument}{acmlarge}{after}{float}
# #+LATEX_HEADER: \usepackage[a4paper,bindingoffset=0.2in,left=1in,right=1in,top=1in,bottom=1in,footskip=.25in]{geometry}
# #+LATEX_HEADER: \renewcommand{\xelatexemojipath}[1]{/home/joe/Downloads/DiscordChatExporter/images/#1.pdf}
# #+LATEX_HEADER: \usepackage[math-style=french]{unicode-math}
# #+LATEX_HEADER: \usepackage{mathtools}
# #+LATEX_HEADER: \usepackage{lscape}
# #+LATEX_HEADER: \setmonofont[Color=blue]{Ubuntu Mono}
# #+LATEX_HEADER: \newfontfamily{\mm}[Color=red]{DejaVu Sans Mono}
# #+LATEX_HEADER: \usepackage[multiple]{footmisc}


\input{title-stuff}
* Abstract                                                        :noexport:
:PROPERTIES:
:UNNUMBERED: t
:END:
<<Abstract>>

- Audience somewhat ready
- Background added, conclusions to add to abstract
- After Action Review OK, let’s do it ourselves
- Title explained in Section 1 — could we put a note about ‘X of X’ (see Leo’s notes)
- What are the broader aims... — "GET GRANTS", "GUIDANCE FOR DISTRIBUTED COMMUNITIES"  E.g., these existing specific distributed communities and methods that we do in the paper; futurists, design, peeragogy, emacs research group; the paper is something like a paper prototype of something we could actually build at some stage.  How best to take it up we don’t fully state but we give lots of leads.
- "We are actually able to help solve problems using these methods!" — Is it practical for patterns community?
- "Fellowship" of methods and communities as the hero.  This could go right into the abstract.
- We’ve removed a bunch of stuff, rephrasing, restructured to flow better.  Leo will wreck everything.  It’s just about ready.  So we don’t need more overhaul.
- Challenges as part of an overview... finish on a positive note?
- Abstract presents our wares, and we’re working on that now.
- We think that the concepts are nicely framed now.  Joe teaser for another paper: rant about "that which arises falls away"
- Last edits Saturday following the ERG check-in
** Red pen before Monday, maybe based on any final feedback from Noorah or others?
- Are there 3 or 4 things in here that we could move elsewhere and just reference?
** Joe soapbox:
- Grant proposal with Abby is very linked
- Second half revision pending.
- Not much need to further discuss the paper... MM has pretty much accepted the paper and wants to develop ideas further.
- Alex is thinking about how to bring these things w/ him into industry, continuing to collaborate with us on research in some form.
- Noorah similarly into practical policy development
- We’d like to put out a new edition of the Peeragogy Handbook sometime, this is pretty closely related to this work
- There could be an ERG remix
** If raising questions are part of the contribution
- Thinking about patterns contextually — what does this mean?
* What do we mean by “Patterns of Patterns”?
<<Introduction>>

What are patterns, anyway?  We can start with Christopher Alexander's
phrase: ``Each pattern is a three-part rule, which expresses a
relation between a certain context, a problem, and a solution''
\citep[p.~247]{alexander1979a}.  He went on to unpack this phrase in
two different ways:
# [fn:: https://wiki.c2.com/?PatternDefinition]

#+begin_quote
/As an element in the world/, each pattern is a relationship between a
certain context, a certain system of forces which occurs repeatedly in
that context, and a certain spatial configuration which allows these
forces to resolve themselves.\medskip

/As an element of language/, a pattern is an instruction, which shows
how this spatial configuration can be used, over and over again, to
resolve the given system of forces, wherever the context makes it
relevant. [emphasis added]
#+end_quote

Patterns in the first sense are basically physical in nature.  We can
observe them in the way sand forms underwater ridges subject to waves
and tides, in photosynthesis, and in metabolism.  Design
comes into play with the second sense.  Leitner summarised how this is
meant to work: ``Patterns are shared as complete methodic descriptions
intended for practical use by experts and non-experts'' cite:leitner2015a.

We now ask: what happens if we think about patterns in the second
sense from the vantage point of the first sense?  Already there are a
number of practical texts that use patterns (in the second sense) to
talk about patterns (again in the second sense): they share methods that aid
in discovery, writing, workshopping, and the broader application of
design patterns.  By contrast we develop a more fundamental analysis,
and only then use this to work towards a new level of practicality.

Granted, the relevant forces are no longer simply physical, but are
socially distributed and culturally determined.  Architects, computer
scientists, and institutional designers have all had very different
things to say about design patterns.  Others who may never have heard
of design patterns have relevant things to bring to the conversation.
Here, we combine patterns with methods that originate in future
studies and elite training, and aim to show how these methods can be
used together to tackle problems both big and small.

In 1999, Alexander spoke to computer scientists about the future of
design patterns and “the generation of a living world”
cite:alexander1999a.  We believe that this should be seen as more than just a metaphor.
Towards realising the promise of design patterns, we aim for an
excavation and reworking of the theory.

# \begin{quote}
# \emph{‘Sir, know that while wandering through the forest I
# saw an ancient path. I followed it and saw an ancient city.
# Renovate that city, Sir!’}—\href{https://suttacentral.net/sn12.65/en/bodhi}{Saṁyutta Nikāya, Connected Discourses on Causation, 12.65. The City}, Quoted in \cite{JGB127}.
# \end{quote}

** Outline of Methods
:PROPERTIES:
:UNNUMBERED: t
:END:
<<outline_of_methods>>

We detail three methods which can help a community carry out
self-evaluation and peer learning.  Each has natural
use-cases when considered in isolation.  When combined, the methods
provide a more holistic mixed pattern, as will be described in due
course.  Our
focus is on scaffolding social perception, cognition, and action (Table \ref{tab:acronyms}).
The tripartite division here mirrors classical
psychology cite:Hilgard1980, and continues to be
relevant in contemporary neuroscience cite:Teufel2020. 

\begin{echo}
\begin{table}[h]
\begin{tabular}{llll}
\emph{Key verbs:}           & perceive       & think            & act\\[.2cm]
\emph{Scientists refer to:}& “sensory” & “cognitive” & “motor” systems\\[.2cm]
\emph{Our implementation:}&
\begin{minipage}{1in}
\textbf{P}roject\newline
\textbf{A}ction\newline
\textbf{R}eview
\end{minipage}&
\begin{minipage}{1in}
\textbf{C}ausal\newline
\textbf{L}ayered\newline
\textbf{A}nalysis
\end{minipage}
&
\begin{minipage}{1in}
\textbf{D}esign\newline
\textbf{P}attern\newline
\textbf{L}anguages
\end{minipage}
\end{tabular}
\vspace{.5cm}
\caption{Three acronyms used in this paper: PAR, CLA, and DPL\label{tab:acronyms}}
\end{table}
\end{echo}

*** Project Action Review (PAR) is the sensory element: systematically gathering and verifying observational data.
:PROPERTIES:
:UNNUMBERED: t
:END:

The Project Action Review is structured around five questions which
members of a community discuss and answer together.  This practice
generates a record of an event, as seen through the eyes of the
participants.  In the moment, the PAR allows us to draw out views
which might have gone unstated otherwise.  Over time, projects which
use PARs improve their chances of staying grounded in reality as
circumstances evolve.  We can additionally use PARs to help check how
effectively we are using other methods.

*** Causal Layered Analysis (CLA) is the cognitive element: giving organization and depth to the enterprise.
:PROPERTIES:
:UNNUMBERED: t
:END:

The goal of this methodology is to achieve a deep and inclusive
understanding by integrating empiricist, interpretative, critical, and
actionable knowledge surrounding a topic of concern.  Without an
integrated understanding, a group runs the risk of getting lost in a
muddle of details.  CLA can pull together information logged in PARs
into a coherent body of self-knowledge.  It can also help to surface
concerns that might remain implicit in pattern language: for example,
CLA could help us understand why we had prized a technological
solution to what, upon consideration, turned out to be a fundamentally
social issue (or vice-versa).

*** Design Pattern Language (DPL) is the motor element: orchestrating and scaffolding action
:PROPERTIES:
:UNNUMBERED: t
:END:

Having carefully analyzed the situation and identified possible
solution pathways, we must plot a course of action that accounts for the
complexities of the situation.  Individual design patterns present
solutions to recurring problems: they can be combined with other
patterns and adapted to different situations.  A DPL is a common
language which a community can use to discuss matters of design; it
serves as a repository of shared knowledge.  The flexibility of DPLs
allows the structure to be customized to our particular circumstances
as they evolve.

** Summary of Findings
:PROPERTIES:
:UNNUMBERED: t
:END:

In the [[Case_study][*Case Study*]] section, we focus on a concrete use case that
combines the three methods to manage and plan a transdisciplinary research
seminar.  This case study provides a detailed practical example that
other projects across the pattern language space may wish to emulate
(or adapt) in their settings.

In the [[Analysis][*Analysis*]], we use CLA to analyse design patterns methods.  The
high-level evolution of the DPL method in response to criticism,
innovation, technical developments, and long-term cultural change has
not been previously studied in an integrated manner.  CLA allows us to
surface the direction of travel of pattern language methods, helping
us integrate foundational perspectives and empirical observation.  We
identify trends within the pattern discourse towards transdisciplinary
thinking and large-scale collaboration; and we connect Alexander's
concept of wholeness with the broader evolution of Western
philosophical thought.  This, in turn, shapes our understanding of
what pattern languages can do in the future, which becomes the focus
of our [[Discussion][*Discussion*]].

** Supplementary Material
:PROPERTIES:
:UNNUMBERED: t
:END:

\begin{echo}
Appendix \ref{appendix-pars} contains a sample Project Action Review.
Several patterns in Appendix \ref{appendix} are referred
  to by name in the text.  Henceforth, text in \textsc{Small Caps}
  references external patterns, whereas ALL-CAPS references patterns
  listed in this paper and the Appendix.
Appendix \ref{flaws-appendix} contains a workshop design that accompanies
the paper and makes some of the ideas within it interactive.
% Footnotes are indicated with numerical markers, while more extensive endnotes appear with alphabeticmarkers.
\endnote{\textbf{To PLoP 2021 Writers’ Workshop attendees:} In particular, we use end notes to stash potential outtakes.
    If you see something here that’s valuable, please let us know, and we may add it back into the paper.  If the material here
  doesn’t help, it may go away in the final submission; i.e., we probably will \emph{not} include endnotes in the final submission!}
\end{echo}

# Clarify punctuation usage?  Certainly with coauthors!

* Background

# Batchelor fits w/ Sarkar, epilogue to Inyatullah
# 

Perception, cognition, and action are necessary functions for all
living beings, and even for robots cite:cassimatis2004integrating.
Some of this thinking can be applied to organisations, as in the work
of Stafford Beer cite:beer1972brain.  However, it is harder to say
what it means to be a well-functioning society; and what it means to be
a good member of a society in a time of crisis is a longstanding question.
Alexander’s hopeful stance on the generation of a living world presently comes up against
a reality in which ‘everything is burning’
cite:batchelor2020embracing.  How are we to understand design patterns
in this present time of crisis?  Stephen Batchelor writes:
#+begin_quote
If I am to take this crisis with the seriousness I feel it deserves,
then I need to align my thoughts and actions. I require a coherent
worldview to provide a rational and ethical foundation for my
behavior. (/ibid/., and in quotes in the following paragraph).
#+end_quote

Perhaps pattern methods could fill part of this need.  On the one
hand, patterns could simply be regarded the paragon of the “technical
mindset”, a growing repository of technical fixes.
Heidegger would contrast this way of thinking with the /poiesis/ of the fine arts.
Thinking at a deeper level, pattern methods also suggest themselves as a
methodology that can help “imagine how human communities might come to
flourish in a radically changed world” and articulate “forms of
collective action that can respond to the climate emergency that
threatens life on Earth”.  As we begin this exploration it is useful
to juxtapose our exploration of patterns against a macro-historical
scale.

#+begin_quote
For Sarkar, there have been four historical ways humans have dealt
with their physical and social environment: either by being dominated
by it, by dominating it through the body, dominating it through the
mind, or dominating it through the environment
itself. cite:inayatullah1999situating
#+end_quote

Along with human societies, community assembly of ecosystems cite:Weiher2011,Capitn2009
and the growth of embryos cite:Franois2010 are two natural examples of processes that have
`futures'.  These natural processes are ordered, not only in space but
also in time.  Reflecting on these examples, we see more clearly why
it is that futurists and designers can benefit by connecting with each
other: in order to work together across time and space at various
scales.  We may also reflect that while science fiction can provide a
`thinking machine' cite:Doherty2020, it cannot by itself provide
historically robust alternatives to the global crises that we face.
Again, we need an approach that integrates thinking with action and
awareness, and that works across scales: from individual agents to
distributed networks.

* Methods
<<methods>>

# \begin{echo}
# \begin{flushright}
# \emph{tl;dr: We detail three methods that decompose the three components of design patterns into practical processes.}
# \end{flushright}
# \end{echo}

Subsections [[par_method]], [[CLA_patterns]] and [[dpl_method]] describe the
Project Action Review, Causal Layered Analysis, and Design Pattern
Languages methods; then subsection [[methods_summary]] pulls them
together as a design pattern.

** Project Action Review
<<par_method>>

The US Army developed a methodology called the /After Action Review/ or
AAR, which they use in training elite soldiers
cite:Training-the-Force.  AARs can be used to assign responsibility
when things go wrong in training activities, and can help people figure
out how to do better next time.  The method has also been used effectively
in business settings cite:learning-in-the-thick-of-it.   As such, After Action Review
shares common ground with the \textsc{Daily Scrum} and
\textsc{Sprint Retrospective} cite:sutherland2019a patterns from Scrum.  However,
it does not have the product orientation of Scrum.
In a distributed peer-to-peer collaboration, we wanted an adaptation of the
AAR that would make it more open ended and horizontal in nature.  We
came up with the following template:

1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?

When we fill in the template, we call it “doing a /PAR.”/  A real-world example is provided in Appendix [[appendix-pars]].
As an
acronym, “PAR” has stood for various things over the years—Peeragogical Action Review, Project Action Review—but we like PAR as
a stand-alone term.  Allusively, it brings to mind the corresponding
concept of /par/ in golf, and helps give us a sense of how we are doing
at any given point in time.[fn:: “In golf, /par/ is the predetermined
number of strokes that a proficient golfer should require to complete
a hole, a round (the sum of the pars of the played holes), or a
tournament (the sum of the pars of each round).”—Wikipedia] Like the
Army, we typically use PARs retrospectively (“what /did/ we
expect to learn or make together?”).  However,
PARs can also be applied to look forward, proactively, as a way to
scaffold anticipation by “remembering the future”
cite:arnkil2008remembering.  In that case, item (5) can be expanded to
include a number of different forward-looking scenarios.

** Causal Layered Analysis
<<CLA_patterns>>

#                                                    "Let’s stick with layer as opposed to level."

Sohail Inayatullah developed Causal Layered Analysis (CLA)
cite:inayatullah1998b,inayatullah2004causal as a research methodology
for examining a topic of concern at four layers that he refers to as
the /litany/, /system/, /worldview/ and /myth/.  Part of the reason we do such
an analysis is that there are different kinds of causes, ranging from
immediate events to deep-seated cultural beliefs.  Inyatullah’s work draws on his
scholarship of P. R. Sarkar cite:inayatullah1999situating.
#+begin_quote
This perspective is derived from Indian philosophical thought...which
asserts that the mind is constituted in shells or kosas. Moving up and
down the shells is a process of moral and spiritual
enlightenment. Going deeper into the mind is an inward process through
which truths are
realized.[fn::https://proutglobe.org/2013/06/the-further-reaches-of-policy-making-cla/]
#+end_quote
In developing a CLA, none of the four layers is
privileged over the others, nor are they examined in isolation.
Rather, one moves between them, examining how they relate to one
another.  One can then integrate these insights to form a more
comprehensive basis for understanding what is happening in the present
and for anticipating the future.

Here, we explain each of the levels according to the following schema:

- *Contents*: /What is found in this layer?/
- *Analysis*: /Techniques for analysis of this layer./
- *Literature*: /Instances of texts which are typically operative at this layer./

To illustrate the four layers and associated techniques, we introduce
a running example of a mom-and-pop pizza shop.

*** Litany

- *Contents*: Observable facts, events, and quantitative trends.
- *Analysis*: Minimal processing of data.
- *Literature*: News reports, tax filings, chit-chat.

**** 🍕 Example, Litany Layer
Imagine a couple who on some of their first dates enjoy going out for pizza. They like different toppings, but that doesn’t particularly matter, because each of them orders their own perfectly sized Neopolitan-style pizza, and eats it with gusto. Indeed, it turns out they like pizza so much that they would like to have it several nights a week. Going out that frequently would be expensive, so they erect a brick oven in their backyard and get good at making their own pizzas at home: selecting good ingredients, fermenting the dough, and baking at a high temperature. After some time goes by, they have gotten really good at this, and they daydream about opening their own restaurant. They look into some available practical guidance and adapt it for their use case. After a lot of planning and a whole lot of work, they get their new pizza restaurant up and running, and they are doing good business. However, as more time goes by, they begin to notice some stress.
*** System

- *Contents*: The social, economic, political, and historical forces which shape events.
- *Analysis*: Technical explanations and interpretation of data within a given paradigm.
- *Literature*: Editorials and policy institute reports.

**** 🍕 Example, System Layer
Mom has practical experience of how restaurants operate coming from summers she spent working in a diner.  Pop is handy with tools, so he can set up and maintain restaurant equipment.  The policies of the town are favorable to small businesses.  The demographics of the town include a number of busy families with children who form a reliable customer base for the pizzeria.  As the pace of economic recovery picks up, townspeople have more money and less time, so they frequent restaurants and order takeout more frequently.  The restaurant maintains good connections with local suppliers, and Mom and Pop are proud of the high quality and affordable dining experience they can offer.  However, they are very, very, busy.

*** Relation of System Layer and Litany Layer
:PROPERTIES:
:UNNUMBERED: t
:END:

The stress mentioned above is an upshot of all of the activity
described.  Business is booming, money is flowing: that’s not the
problem.  However, some confusion has ensued about who should be
managing the restaurant, on what days, where to get the ingredients,
and how much they should spend.  Here we get a sense of what’s missing
at the system level, namely, they haven’t yet found a systematic way to sort
out the confusion.

*** Worldview

- *Contents*: Core values and attitudes which motivate choices and
  actions.
- *Analysis*: Uncover deep assumptions and study the mental and
  linguistic constructs which undergird how people interact with each
  other and their surroundings.  Compare and critique paradigms and
  discourses.
- *Literature*: Works of philosophy and critical theory.

**** 🍕 Example, Worldview Layer
Pop values self-reliance and self-cultivation. For him, the worth of a person is determined not by possessions, external circumstances, or social status, but by character and accomplishments. He believes that every person has an inner purpose and that the surest way to be happy and useful to society is to follow one's inner voice and encourage others to do the same. Mom values relationships and community. Her goal in life is to make the world a better place by bringing people together and slowing down the pace of life at least long enough to let neighbors chat and get to know each other. Pop, inspired by historical figures like Thoreau, sees living “off-grid” as an ideal: a way to be independent from modern civilization, and more in touch with nature.  It can be hard for him to reconcile his community spirit with his individualism.  Mom, on the other hand, envisions an ideal community where healthy relationships are facilitated over good meals.  She sees the restaurant as a way to build relationships with diners and others in the food supply chain and local community.
*** Relation of Worldview Layer and System Layer
:PROPERTIES:
:UNNUMBERED: t
:END:

Earlier we looked at the choices that the couple made, relative to their experiences, environment, and background.  Now we see some of the deeper reasons for those choices. Despite the difference in approach and outward orientation, both Mom and Pop have worldviews which are fundamentally oriented towards people: most of the time they get along well, and they enjoy working together.  However, their two worldviews—while not disjoint or necessarily in conflict—are not automatically well aligned; nor are they automatically well-suited to the new situation that has evolved now that they are small business owners.  If the couple wishes to resolve the stress that they are facing, they would be wise to wonder if their problems originate at an even deeper level: one which they have not explored together before.

*** Myth
- *Contents*: The symbols and tales which give meaning to life.
- *Analysis*: Study meaningful symbols and the myths and rituals within which they participate.
- *Literature*: Poetry, art, anthropology, Jungian analysis.
**** 🍕 Example, Myth Layer
Pop looks up to Thoreau and Emerson as personal heroes, and knows /Walden/ and /Self-Reliance/ backwards and forwards.  Mom has fond childhood memories of parents who loved cooking together, and her memories evoke an age of innocence.  For her, the circle is a powerful symbol of wholeness and community: when she brings a pizza to children at the round tables of the restaurant, she feels like a mystagogue initiating the next generation.
*** Relation of Myth Layer and Worldview Layer
:PROPERTIES:
:UNNUMBERED: t
:END:

Innovation at the myth layer supports an adapted worldview that
introduces new patterns into their daily and weekly rituals, along
with new sources of meaning.  Mom and Pop decide to close the shop Monday
through Wednesday, to spend time away from the business, as part of a
new weekly cycle that mirrors the seasons.

# They engage with hobbies like writing, woodwork, and painting, and
# they tend their garden together.  Thursday through Sunday, they
# resolidify their intention to make their work together a meditation on
# love. They develop new ideas, related to food and otherwise.  Boosted
# by their time off, they prepare more innovative meals and, while the
# restaurant remains affordable, they garner enthusiastic crit from
# foodies.

** Design Pattern Languages
<<dpl_method>>

The two senses of ‘pattern’ mentioned above—‘As an element in the /world/...’ and
‘As an element of /language/...’—are mirrored within the
concept of a design pattern.  Like an ellipse, the design pattern has
two main foci: context and community.

- /Context/ shapes and constrains the type of activity which is being considered, be it designing a building, writing software, or something else.
- /Community/ encompasses the stakeholders --- experts and non-experts alike --- who are involved with or affected by a particular project.

Integral to the basic concept of a design pattern is a third feature
that describes the interaction of the community and the context.  The
community uses the pattern to overcome some real or potential /conflict/
that they experience within this context.  The conflict is also
referred to as a /problem/; its resolution is described as a /solution/.
Alexander and Poyner emphasised that ‘design’ is not needed when the
conflict can be resolved in an obvious or straightforward manner.  For
example, you typically would not need a design process surrounding
/sitting in a chair/,
\begin{echo}
because “under normal conditions each one of the
tendencies which arises in this situation can take care of itself”
\citep[p.~311]{alexander1970a}.\endnote{The straightforwardness of sitting in a chair notwithstanding, Thich Nhat Hahn has written a book called \emph{\href{https://www.penguin.co.uk/books/111/1111997/how-to-sit/9781846045141.html}{How To Sit}} (2014): this somewhat proves Alexander’s point as the exception to the rule.  However, prior to reading this book one might want to read /How to Read a Book/.}
\end{echo}

All of this means that design patterns need to achieve something
fairly subtle.  Each represents the synthesis of a repeatable solution
to a type of conflict which itself repeats within a particular
context.  Furthermore, it does this in a way that makes the solution
teachable, learnable, and otherwise replicable within a given
community.  However, if the design pattern makes the solution to the
problem too obvious, then design, /per se/, is no longer needed!\endnote{For example, Peter Norvig argued that we see fewer of the design patterns typical of Object Oriented programs inside programs written in functional and dynamic languages, because these languages embed many of the typical OO patterns as language features.} We
might say that the design pattern carries with it a fragment of
irreducible complexity.  This perspective may or may not be
surprising.

Alexander had described the need for patterns when things get complex
cite:alexander1964notes.  He specifically focuses on what could be
called “horizontal” complexity, a situation where there are a lot of
moving parts and relations between them.  Methodologically this is
elaborated with the notion of a /pattern language/.\endnote{The issues involved become somewhat more complex when there are multiple DPLs interoperating, but are not fundamentally different.}
Pattern languages have a property of unfolding, from more general to
more specific.  However, they do not necessarily cover deeper forms of
“vertical” complexity, where there are deep historical or ontogenetic
causes, feedback loops, or complex conceptual issues which are not readily
expressible in design-pattern-theoretic terms.  Let’s have another
look at these issues by way of two contrasting metaphors.

The first metaphor comes from Christian Kohls, who proposed to treat
each design pattern as a journey: “a path as a solution to reach a
goal” cite:kohls2010a.  In this metaphor, design patterns are
understood to have an initial condition and an end condition, defined
within some context. The context also associates a cost to traversals
of paths.  There are several associated problems: the elementary
problem is to traverse the terrain and travel from the start state to
the end state.  The next problem is to do this at low cost.  The third
problem is to find a reliably repeatable way to do this.  A fourth problem is to describe the process in such a way that the path
can be traversed by others.

The second metaphor comes from Joseph Campbell, who described an
“archetypal pattern” cite:shalloway2005a, one that can be found
embedded in myths and stories across diverse cultures and historical
periods.  The “hero’s journey” is also described with a path
cite:campbell1949a, however, in this case the path runs in a circle,
and the journey focuses on the transformations of the hero who
traverses it.  Although an account of the journey can be shared,
traversal is effectively single-use.  The cost is typically “high.”
Nevertheless, once a myth or metaphor is established in a shared
narrative, the journey can be reenacted through ritual or engaged with
in other ways that solve a range of social problems
cite:handelman1998a. In short, the difference between these two
traversal stories suggests that the process of finding “the path that
is capable of leading to a good structure” cite:alexander1999a may
contain irreducible complexity—even when sharing the information
about the path is relatively simple.

** Summary
<<methods_summary>>
We are
now in a position to explain how PAR, CLA, and DPL combine into one holistic
pattern, in Leitner’s sense of a complete methodic description.  We
will write this down using the classical DPL format: describing the
associated /context/, the /problem/ denoting a conflict, together with a
/solution/.  As it happens, the three acronyms can be combined and
remixed in a clever way to provide a title for this pattern.  This
accurately suggests that the methods need not be run in a fixed order,
but are interwoven together.

*** PLACARD
:PROPERTIES:
:UNNUMBERED: t
:END:
<<PLACARD>>
- *Context*: In the course of working on a project together: /we use the PAR to get a sense of our working context/.
- *Problem*: Although we may encounter many difficulties in this context, our effort to understand them faces a central *challenge*, namely the fact that the problems span different layers and scales of complexity, so it can be hard to understand where the difficulties actually come from: accordingly, /we use the CLA to understand and frame the problems and their interconnections/.
- *Solution*: Once we have grasped the problem, we need to elaborate an actionable solution that remains adaptable to ongoing changes in the context: /we use DPL to elaborate the solution/.

\begin{wrapfigure}{l}{0.5\textwidth}
\centering
\vspace{-.8\baselineskip}
\includegraphics[width=.5\textwidth]{placard.jpg}
\caption{\label{fig:placard}Mnemonic illustration of the \hyperref[PLACARD]{PLACARD} pattern\vspace{-1\baselineskip}}
\end{wrapfigure}

Figure \ref{fig:placard} provides a mnemonic.[fn:: For French speakers, /placard/ means ‘cupboard’, and there is an idiom, /placardisé/, which refers to an employee whose tasks all have been reassigned to others; the import is similar to the English idiom ‘put to pasture’. While it is not the case that [[PLACARD][PLACARD]] reassigns all DPL functions to other methods, the French idiom is potentially suggestive as another mnemonic.] The main thing to notice is that using the three methods
together helps to make the design pattern method practicable.  We can use the
PAR to move from a context to a “Context”, established and written
down.  We can use CLA to move from a situation of concern to a
situation in which the core “Problem” or “Problems” can be thought
about.  However, the fact that DPL shows up inside of [[PLACARD][PLACARD]] without further elaboration may be somewhat
concerning.
\begin{echo}
The reader may be wondering: “I think I can see how the methods that have been discussed could help in understanding
the \textbf{context} and the \textbf{problem}, but is there anything here that actually helps with formulating \textbf{solutions}?”\endnote{\textbf{JC@coauthors:} I’m still a bit concerned about this!}
\end{echo}
This is certainly a worthy concern, and something we will come back to in Section [[erg-summary]], after looking at an example of the [[PLACARD][PLACARD]] pattern in use.


* Case study: Planning “Season 1” for the Emacs Research Group
<<Case_study>>

This section summarises the concrete application of the methods
from Section [[methods]] within an active seminar, the Emacs
Research Group (ERG), which was convened following EmacsConf
2020.[fn:: https://emacsconf.org/2020/; the conference took place November 28th and 29th of 2020.]
We illustrate how the
three methods introduced above interoperate.  In our case, this
analysis has allowed us to develop a trajectory for the project.
As a case study, this section is a more-or-less
self-contained example and shows how mixing the three methods
gives us more than the sum of the parts.

In the ERG, we think of the work carried out up to this point as
*Season 0*, on the view that so far our thinking has developed
rhizomatically, underground, rather than fully in the public sphere.
The following analysis serves to contextualize our work relative to
the PLoP and Peeragogy communities.  Over the 25 sessions of our
seminar to date, we used CLA in combination with PARs to address the
question ‘What is our vision for change and how is progress
measurable?’.  More specifically: we did a PAR at the end of every
(approximately weekly, two-hour) session.[fn:: Data archived at
https://github.com/exp2exp/exp2exp.github.io, with meeting notes and
PARs indexed and viewable on the web at
https://exp2exp.github.io/erg.]  This allowed us to track progress,
and to surface key issues and concerns.  For example, bootstrapping needs
related to scheduling and collaboration tools, along with persistent
questions about how best to go public, are documented in our first
PAR, which is reproduced in Appendix \ref{appendix-pars}.  Every six weeks
or so, we merged selected bullet-points from our PARs into the CLA
outline in an intuitive way, depending on which section they seemed to fit best.
\begin{echo}
We also elaborated those bullet points into a narrative form,
which we revised to accommodate new data as time went on.
We also began to develop TODO items that would make the
next steps for this seminar group both actionable and meaningful.\endnote{The Peeragogy approach to patterns
is aligned with the feminist principle that all knowledge is incomplete (\url{https://mitpress.podbean.com/e/experiments-in-open-peer-review/}, minute 5).
A “living” pattern is, accordingly, attached to Next Steps that would help to realise that pattern within a
context; when we don’t have any next steps, we put the pattern in a \textsc{Scrapbook}.}
\end{echo}

Here, we collate these next steps with peeragogy design patterns like \textsc{Roadmap}
cite:peeragogy-handbook-long.[fn:: See http://peeragogy.org/top for a
reworking of the /Peeragogy Handbook/ as a unified pattern language,
which extends the earlier presentation in cite:patterns-of-peeragogy.]
\begin{echo}
To make the way this process works somewhat more clear to the reader, we include the data supporting the CLA from PARs carried out in our 1\textsuperscript{st}, 10\textsuperscript{th}, and 18\textsuperscript{th} sessions (marked with ①, ⑩, and ⑱ below).
% \footnote{We did two PARs during the eighteenth session.}
\end{echo}
By the time of our fourth iteration of the larger
$\mathrm{PAR}\rightarrow\mathrm{CLA}$ cycle, each section had
accumulated around 20-30 bullet points of supporting data at a similar level of
granularity.

# We elaborate new patterns where
# there is no match for our current needs; one per CLA section:
# [[FORMAL PATTERNS][FORMAL PATTERNS]], [[SERENDIPITY][SERENDIPITY]], [[RECOMMENDER][RECOMMENDER]] and [[DIVERSITY][DIVERSITY]].  We also
# cross-reference each of the TODO items with the most closely
# associated patterns from the poststructural futures toolbox
# from Section [[CLA_patterns]].  This shows how the lines of
# thinking that underpins the CLA method can inform further
# action: *Season 1* will be shaped by this narrative and the
# corresponding TODO items.

The following four subsections present the result of applying the
methods described above.

** Understanding data, headlines, empirical world (short term change)

We’ve made progress since we started with the raw themes of *Research
on/in/with Emacs* back in December 2020.  We’ve met almost every week
since then, and interviewed some interesting and varied guests.  We
have a clearer idea of what we want to talk about at the next
EmacsConf, and how we can be of service to researchers and Emacs
users.  We have been using a workflow that helps us carefully review
progress, diagnose issues, and manage our energy.  The next phase of
this project is to “go public” and mesh with ongoing related
activities elsewhere, including by getting some training events up and
running.
# [fn:: Our plans for *Season 1* should allow flexibility for [[REORDERING KNOWLEDGE][REORDERING KNOWLEDGE]], since we may all be thinking about things differently, and we will have different outside commitments. This will allow us to develop a [[GENEALOGY][GENEALOGY]] of the themes and actions we are developing. This helps to realise the [[DISTANCE][DISTANCE]] pattern, since we can understand our efforts through the eyes of others. This helps to realise the [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND FUTURES]] pattern, because we better understand how the project looks for someone who is just getting started now. A suitable degree of formality can assist with [[REORDERING KNOWLEDGE][REORDERING KNOWLEDGE]], see further details in the [[FORMAL PATTERNS][FORMAL PATTERNS]] pattern.]

*** Representative supporting data
:PROPERTIES:
:UNNUMBERED: t
:END:
\begin{itemize}
\item[①] \emph{Everyone shared a brief intro and ideas so we got to know each other}
\item[⑩] \emph{We’ve brainstormed a couple of options for getting out there: White-papers, Grants, Journal papers (very concrete)}
\item[⑱] \emph{Alex: My major intention was to meet you guys and learn something, wanting to reinforce existing knowledge of emacs and develop it further}
\end{itemize}

*** Next Steps
:PROPERTIES:
:UNNUMBERED: t
:END:

| Maintain plans for the next six months                  | \textsc{Roadmap}     |
| Keep doing PARs and CLAs                                | \textsc{Assessment}  |
| Mesh with other ongoing activities elsewhere            | \textsc{Cooperation} |
| New user workshops: “Zero to Org Roam”                  | \textsc{Newcomer}    |
| Come up with a categorical treatment of todo-categories | [[FORMAL PATTERNS][FORMAL PATTERNS]]      |

** Systemic approaches and solutions (social system)

If we tackle big enough projects, it will bring with it the need for
collaboration.  We like to create tangible deliverables (e.g. journal
articles). However, “If we knew what the outcome was, it wouldn’t be
research”—therefore, we’re focusing initially on research methods
and design documents. That may result in a longer time to write
initial papers, but when something is released it is more thoroughly
prepared. Meanwhile, we keep our skills sharp by fixing bugs,
improving our own workflows, and actively exploring the landscape. All
these activities are part of the system we implement regularly, which
minimizes technical debt and allows space for serendipity to occur.

*** Representative supporting data
:PROPERTIES:
:UNNUMBERED: t
:END:
\begin{itemize}
\item[①] \emph{Part of a greater sense of trying to do something with EmacsConf to federate the community}
\item[①] \emph{Joe: Leo did an amazing job facilitating the meeting}
\item[①] \emph{Public Policy conference: (How to get a grant?)}
\item[⑩] \emph{Potential interview with Leo \& Jethro Kuan (co-maintainers of org-roam)}
\item[⑱] \emph{Leo did a nice job of intervening}
\end{itemize}

*** Next Steps
:PROPERTIES:
:UNNUMBERED: t
:END:

| Identify potential stakeholders in Emacs Research               | \textsc{Community}          |
| Identify stakeholders in the kind of activities we can support  | \textsc{A Specific Project} |
| Identify venues where we can reach these different stakeholders | \textsc{Wrapper}            |
| Create some publication to plant a flag for our group           | \textsc{Paper}              |
| Keep exploring!                                                 | SERENDIPITY                 |

** Worldview, ways of knowing and alternative discourse
<<erg_worldview>>

We have looked at RStudio and Roam Research as models of (some of) the
kinds of things we think Emacs can learn from and eventually improve upon.
‘Practice’ and ‘method’ keep coming up in our discussions as,
respectively, ‘more bottom up’ and ‘more top down’ ways of actualising
things.  Concretely, we’ve been studying our own processes and looking
for the tools and settings that are the most conducive to the work we
want to do.  For example, instead of having a single Org Roam
directory shared via Git, what if we had ways of managing sharing of
notes across ‘graphs’?

Collaboration is familiar to teams across all domains. Even authors
working alone will collaborate with their past and future selves. What
is common for all collaborators is that the transfer of information
must be uninhibited.  If we all had our slipboxes online, we could
interlink them.[fn:: The zettelkasten (German: “slip box”, plural zettelkästen) is a method of note-taking and personal knowledge management used in research and study.  ([[https://en.wikipedia.org/wiki/Zettelkasten][Wikipedia]])]  This would generalise *ORCiD*, and allow people to
reference processes that are undergoing evolution.  Maybe a service
like this would turn into a ‘Tinder for academics’—helping to match
people based on their interests (or similar people in different
fields).  So, what’s the price point?  Instead of paying money to go
to conferences, now we can spontaneously make conferences and
workshops.  As a guess, $750.0 per user per year might be a fair price—for those who can afford to pay it—if the service helps people to
do better research and saves a bunch of travel.  We could also set up
a pricing model proportional to each country’s carbon emissions or
something like that.
# [fn:: Whereas these are existing commercial packages, some of the workflows could be restructured and, e.g., made more accessible or potentially more powerful through integration with other open tools. This is a way of [[REORDERING KNOWLEDGE][REORDERING KNOWLEDGE]] at the level of projects and business operations. We recognise that we’re all coming from different places with [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND FUTURES]].  How can our workflow better reflect that? Can we engage in an ongoing [[DECONSTRUCTION][DECONSTRUCTION]] of the methods as we use them? (Admittedly, a little bit like rebuilding the plane while it is still flying, but with some care it should be possible.) We can think about different ways of approaching knowledge construction as a way of deepening the [[GENEALOGY][GENEALOGY]] pattern in practice. By developing a paper that situates our work in a wider context we develop some [[DISTANCE][DISTANCE]] from the closed-doors of *Season 0* and engage more creative thinking (and others’ views on!) *Season 1*. Clearly, this is a way to operationalise [[REORDERING KNOWLEDGE][REORDERING KNOWLEDGE]]; see further details in the [[RECOMMENDER][RECOMMENDER]] pattern.]

*** Representative supporting data
:PROPERTIES:
:UNNUMBERED: t
:END:
\begin{itemize}
\item[①] \emph{Wonderful outcome from attending EmacsConf 2020!}
\item[⑩] \emph{Anthropology + Psychology is a special nightmare for reproducibility}
\item[⑩] \emph{Maybe the ERG could contribute further patterns?}
\item[⑱] \emph{But there’s a problem with Emacs, which is that there isn’t proper intro}
\end{itemize}

*** Next Steps
:PROPERTIES:
:UNNUMBERED: t
:END:
| Spec out the Emacs based ‘answer’ to RStudio, Roam Research                  | \textsc{Community}  |
| Develop our own intention-based workflow                                     | \textsc{Forum}      |
| Continue to develop and refine our methods                                   | \textsc{Assessment} |
| Product and business development plans for a multigraph interlinking service | \textsc{Website}    |
| A tool to find and match peers/content                                       | RECOMMENDER         |

** Myths, metaphors and narratives: imagined (longer term change)

In our concrete methods, we have aligned ourselves with the ‘[[https://longtermist.substack.com/][long-term
perspective]]’.  This includes both retrospective and prospective
thinking.  For example, the things that were timely 7 years ago might
not be so timely now; in many cases the relevance of a given
innovation goes down over time.  However, Emacs has an evolutionary
character that has allowed it to keep up with the times—becoming
more relevant and useful ever since Steele and Stallman started to
systematise [[https://www.oreilly.com/openbook/freedom/ch06.html][Editor MACroS]] for the Text Editor and Corrector (TECO)
program.  Not only has the technology evolved, but so has the social
setting in which this work is done.  Whereas the concepts underlying
the free software movement were based on “[[http://www.gnu.org/software/emacs/emacs-paper.html][communal sharing]]” of source
code, these methods can be extended and allow us to synthesise new
relationships within broader semiotic commons.  Emacs can become part
of a system for addressing large-scale existential problems, by
expanding the frontier of what’s possible for human beings.
# [fn:: As we develop the relationships of Emacs to its context, the process can operationalise [[DECONSTRUCTION][DECONSTRUCTION]]. We referenced \textsc{Assessment} above with regard to PARs and CLAs; here we can imagine other techniques for assessing learning, thinking across [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND FUTURES]] in which these methods become more embedded in technological workflows. One way to proceed could be through a [[DECONSTRUCTION][DECONSTRUCTION]] of the practices of free/libre/open source; see further details in the [[DIVERSITY][DIVERSITY]] pattern.]

*** Representative supporting data
:PROPERTIES:
:UNNUMBERED: t
:END:
\begin{itemize}
\item[①] \emph{We generally agreed that we want to make something that exposes intrinsic value of using these tools}
\item[⑩] [None recorded at this level from this PAR.]
\item[⑱] \emph{But there was no such guidance; you were in the middle of an alien playground. “But I just wanted to do my Clojure stuff.”}
\end{itemize}

*** Next Steps
:PROPERTIES:
:UNNUMBERED: t
:END:

| Survey related work                                                 | \textsc{Context}    |
| Assess what we’re learning                                          | \textsc{Assessment} |
| Think about how we can help improve gender balance in Free Software | DIVERSITY           |

** Summary
<<erg-summary>> The narrative paragraphs at each level describe
abstract patterns occurring among, and mutual accommodation between,
the bullet points that developed in our PARs.  The Next Steps
typically do not represent concrete objectives, for instance in a
‘S.M.A.R.T’ format.[fn:: Specific, Measurable, Achievable, Realistic,
and Time-bound (Wikipedia)] They are, rather, descriptions of
anticipated patterns of behaviour—here linked to /bona fide/ design
patterns.  To refine these items into tasks that are concretely doable
within the upcoming *Season 1* will require further breakdown and
elaboration.  We foresee this to be an iterative process, assisted by
bidirectional links between patterns and next steps.

Software tools will help with this, though our current prototypes
could certainly be improved.  These prototypes are based on Emacs’s
built-in Org Mode (a tool for managing information structured in
outlines), Org Roam[fn:: [[https://www.orgroam.com/]]] (an Emacs package
layered on Org Mode and used for creating zettelkasten, which are,
essentially, wikis), and Org Roam Server (a further layer for
visualisation of the resulting network structures).  As described in
Section [[erg_worldview]], these tools have some deficiencies when it
comes to interlinking varied contents—such as patterns and next
steps—from distributed sources.  In short, we need to keep improving
our tools in order to effectively manage growing distributed,
interlinked, collections of PARs, CLAs, and DPLs, alongside other
scientific and technical corpora.  Federated Wikis comprise another area
of work where these concerns are being approached in technical terms
cite:esfandiari2016distributed,cunningham2013a.

Looking back over the case study, we can now outline an answer to the
concern raised at the end of Section [[methods]], namely how do the
[[PLACARD][PLACARD]] methods help, concretely, to develop solutions?
Broadly, a solution process can often be decomposed into interrelated
subtasks cite:alexander1964notes,polya1945solve,polya1954plausible.
\begin{echo}
A standard problem-solving methodology is to understand the \mbox{(sub-)}context and
\mbox{(sub-)}problems in detail—along with their relationships to other parts
of the developing decomposition—and on this basis make predictions about the way
an intervention could change the overall system.
\end{echo}
As we saw in the references to /practice/ and /method/, above, and will
revisit again later on in the paper, there are “two different forms of
information processing (bottom-up and top-down)” cite:Teufel2020.  CLA
can help with both, and in so doing can indeed assist with
solution-development.  Nominally, CLA is an analytic tool that
decomposes a problematic situation into /layers/, and /causes/ operating
at and between these layers.  In this sense it functions top-down.
However, CLA also plays a synthesis role.  Whereas we could compare
the PAR to a tangent vector or derivative that gives a momentary
reading of how things are going at a given point in time, CLA can be
used to integrate these observations into an overall plan—as we’ve
seen above.

* Analysis: CLA applied to Design Pattern Language literature and practices
<<Analysis>>

# \begin{echo}
# \begin{flushright}
# \emph{tl;dr: We study Design Pattern Languages practices using Causal Layered Analysis.}
# \end{flushright}
# \end{echo}

In the previous section we narrowed our attention to the Emacs
Research Group and developed a Causal Layered Analysis built by
studying the PARs we had carried out.  We connected the results with
Peeragogy patterns as a way to check our work, connect with a
broader community, and maintain plans for the future.  In this section, we will broaden our gaze
considerably further.  Although the two sections traverse different
scales, a CLA of the design pattern community can, subsequently, be
compared with what we saw above, and this cross-scale comparison
yields new perspectives.  In précis, in this section:
- We will look at queries raised by Alexander and his collaborator Bryant, along with a systematic analysis of criticisms of pattern methods collected by Dawes and Ostwald.
- We examine issues related to how people share and discuss patterns, as well as the changing way in which these discussions have been framed at PLoP.
- We examine a worldview linked with patterns through the lens of mob software and its critiques.
- Lastly, we look at some symbols and philosophical traditions that enrich our understanding of the context in which Alexander developed his methods.

Practical next steps linked to patterns (as in the previous section)
could be developed in later work.  We discuss some likely directions
for development in the following sections.

** Litany: Understanding data, headlines, empirical world (short term change)

# ¶¶¶ Peace movement vs Anti-war movement: issues of identity after "success"

The first layer in CLA is the *litany layer*: it describes the problems
that people are well familiar with.  In the case of the design
patterns discourse, this level includes—in particular—the familiar
kinds of conflict-based problems that are described in patterns and discussed
at PLoP, along with higher-order problems of application, and debates about these (e.g.,
ranging from Christopher Alexander’s “\textsc{Entryway Transition}” pattern to
his remarks about how people who attempted to apply his methods
ended up placing “alcoves everywhere”, etc.). This layer is sometimes
also referred to as the *problem level*: in the patterns discourse,
problems abound.  Indeed, one of the core attributes of the pattern community is that it
is not only comfortable with problems but that it actively seeks them
out with a ‘problematizing’ discourse.

Not all of the well-known and discussed problems have been solved.
For example, ‘Alexander's
Problem’, as described by his collaborator Greg Bryant, is that:
#+begin_quote
... despite all of the tools he created, his penetrating research, his
many well-wrought projects, and his excellent writing, he did not
manage to grant, to his readers, the core sensibility that drove the
work. He also did not organize the continuance of the research program
that revolves around this sensibility. cite:bryant2015
#+end_quote
Attempts to work out a practical solution to this problem are
developing.[fn:: https://www.buildingbeauty.org/ and
https://www.buildingbeauty.org/beautiful-software] Coming at the same
basic issue from a more visionary standpoint, Alexander framed this
query for the programmers who were using pattern methods at the turn
of the millennium:
#+begin_quote
What is the Chartres of programming? What task is at a high enough
level to inspire people writing programs, to reach for the stars?
cite:alexander1999a
#+end_quote
More recently, Dawes and Ostwald cite:dawes2017a develop an
elegant taxonomy of criticisms of the pattern method.  In
outline, their taxonomy covers criticisms at the following three
layers:
- Conceptualisation :: Ontology, Epistemology \newline /(e.g., “Rejecting pluralistic values confuses subjective and objective phenomena”)/
- Development and documentation :: Reasoning, Testing, Scholarship \newline\hfill /(e.g., “The definitions of ‘patterns’ and ‘forces’ are inexplicit”)/
- Implementation and outcomes :: Controlling, Flawed, Unsuccessful \newline\hfill /(e.g., “Patterns disallow radical solutions”)/

By showing how the criticisms relate to one another, Dawes and Ostwald
begin to develop a [[GENEALOGY][GENEALOGY]] at the level of critical perspectives.
The critiques they examine show that there is not just one pattern
discourse, but many.  In a parallel work the same authors analyse the
structure of Alexander’s classic text, /A Pattern Language/ (/APL/) and develop
three alternative perspectives on /APL/'s contents, which they refer to
as the *generalised*, *creator*, and *user* perspectives cite:Dawes2018.
These perspectives amount to different techniques for [[REORDERING KNOWLEDGE][REORDERING
KNOWLEDGE]].  We will elaborate at the next level.

** System: Systemic approaches and solutions (social system)
The *system* layer is typically understood in terms of the *social
phenomena* that cause the problems at the litany layer to emerge (along
with their familiar solutions).  In the original setting in which
patterns developed, this layer would have included causes such as more
people living in cities, combined with the possibility of developing a
more community-driven approach to design using contemporary
technologies.  In short, at this level, we examine where the familiar problems come from.

Dawes and Ostwald’s cite:Dawes2018 central finding is that many patterns in which
Alexander had medium or low confidence in fact occupy a relatively
central position in /APL/'s graph:

#+begin_quote
... the patterns which are most likely to be encountered by designers –
are most easily accessed, or provide greatest access to other patterns
– might be those which Alexander acknowledged were incapable of
providing fundamental solutions to the problems they addressed.
#+end_quote

This means that novice users could be expected to encounter problems
in application of /APL/'s patterns: “despite its often authoritative and
dogmatic tone, Alexander’s text was framed as a work in progress,
rather than a definitive design guide” (p. 22).  Dawes and Ostwald
suggest that their analysis could point to “prime opportunities to
continue the development of /A Pattern Language/'' (p. 21).

\begin{echo}
Here, a range of media issues begin to crop
up.\endnote{At this point it is also useful to recall that there are a
range of ‘other’ pattern discourses which could be relevant to
understanding how the problems emerge: here, ‘other’ is intended in
the sense mentioned in our \hyperref[REORDERING KNOWLEDGE]{REORDERING KNOWLEDGE} pattern, i.e., pointing to other communities who are not in
close touch with PLoP: these include PurPLSoc and the world of
practicing architects.}
\end{echo}
Broadly put: there have been some attempts at
creating systematic archives of patterns cite:koppeRepos,inventadoRepos, but these
efforts haven’t always garnered significant buy-in.
Importantly, the first-ever Wiki was developed in connection with a
platform for developing, sharing, and revising pattern languages
cite:cunningham2013a.[fn:: http://wiki.c2.com/?PeopleProjectsAndPatterns][fn:: http://c2.com/ppr/]
However, there was a distinction between the discussions and the finished patterns.  In the 2013 retrospective,
Ward Cunningham and coauthor Michael Mehaffy write:
#+begin_quote
The original wiki technology functioned in a direct open-source mode,
which allowed individuals to contribute small pieces to incrementally
improve the whole. (/ibid./)
#+end_quote
This is true if by “open source” we understand what you see when you click Edit—but
the statement could be misleading relative to contemporary usage, which is often linked with
the Open Source Initiative’s definition, which centers on the premise that
“Open source doesn’t just mean access to the source code.”[fn:: https://opensource.org/osd]
On the =c2= wiki, licensing was restrictive. Discussions were to take place in “letters and replies” rather than revision or annotation of the published patterns; rights associated with the finished patterns were closely guarded.[fn:: http://c2.com/ppr/titles.html][fn:: http://c2.com/ppr/about/copyright.html]

Although Wiki technology could in principle have been a site for
ongoing [[DECONSTRUCTION][DECONSTRUCTION]] of patterns, this hadn’t happened on =c2=.
This is itself interesting and worth deconstructing a bit.  Notably,
there were only /four/ published “letters and replies”.[fn::
http://c2.com/ppr/letters/index.html] Unfortunately, we could not find
a public archive of the design patterns mailing list where further
discussions took place.  This suggests certain factors of contingency
in the development of the discourse.  Over the years, some of these concerns have been addressed—e.g.,
through the introduction of Federated Wikis and new licensing
models—and other issues and concerns came to the fore.

Dawes and Ostwald’s cite:Dawes2018 remarks on multiple perspectives on
pattern languages resonate Jenifer Tidwell’s charges against the Gang
of Four:

#+begin_quote
... the reality of a software artifact that the developer sees is not
the only one that's important.  What about the user's reality?  Why
has that been ignored in all the software patterns work that's been
done?  Isn't the user's experience the ultimate reason for designing a
building or a piece of software?  If that's not taken into account,
how can we say our building -- or our software -- is “good”? — “The Gang of Four Are Guilty”[fn:: [[http://www.mit.edu/~jtidwell/gof_are_guilty.html]]]
#+end_quote

Notice that the /user/ of the designed artefact has entered the
story as a different figure from the user of the pattern language,
whom we met above.  Tidwell’s critique suggests at least a
couple [[ALTERNATIVE PASTS AND
 FUTURES][ALTERNATIVE PASTS AND FUTURES]]: e.g., what if the end-user had been
placed at the centre the whole time?  Alternatively, what if the
primary focus of patterns was to facilitate interaction between
different stakeholders?  The fact that Tidwell’s book
cite:tidwell2010designing and an essay by Jans Borchers cite:borchers2008pattern
which drew inspiration from her critique both have over
1000 citations on Google Scholar shows that Tidwell’s perspective has
been impactful.  To get a sense of how the pattern community may have
been informed by this critique—alongside other related trends and concerns—we can look at
how the Writers Workshops at PLoP have evolved over time.  In Table [[tabplop]], a
selection of titles of workshop sessions show how the focus of PLoP evolved from
primarily ‘programming’ oriented to a much broader contextual view
over time.  Indeed, by 2019, the focus is almost exclusively ‘contextual’.
The way the themes under discussion have evolved brings to mind the layers of CLA.

#+NAME: tabplop
#+CAPTION: Evolution of PLoP Writers Workshop topics in selected years: CLA in the wild?
| *1997*                        | *2011*         | *2015*                            | *2019*               |
| Architecture                | Architecture | Pattern Writing                 | Group Architecture |
| Roles and Analysis          | Design       | Software Architecture & Process | Culture            |
| People and Process          | Information  | Cloud & Security                | Meta               |
| Domain Specific Techniques  | People       | Innovation & Analysis           | Education          |
| OO Techniques               | Pedagogy     | People & Education              |                    |
| Non-OO Techniques           |              |                                 |                    |

\rowcolors{2}{gray!25}{white}
** Worldview: ways of knowing and alternative discourse

The next layer comprises *worldviews* (e.g., Alexander’s view that
“There is a central quality which is the root criterion of life and
spirit in a man, a town, a building, or a wilderness”).

The situation with licensing on =c2= is particularly interesting in
light of Alexander’s perspective that /APL/ was a “living language”.  In
principle, Wiki technology might have presented the opportunity to
realise this vision fully for the first time, in a virtual setting.
Wiki technology did become widely influential when it was combined
with a free content license on Wikipedia (originally GNU FDL, later
CC-By-SA).

Fast-forwarding to the present day, Christopher Alexander’s website
=patternlanguage.com= writes about [[https://www.patternlanguage.com/membership/memberstour3-struggle.html][The Struggle for People to be Free]]—but it is not referencing freedom in the GNU sense.

In 1979 he was concerned: “Instead of being widely shared, the
pattern languages which determine how a town gets made becomes
specialized and private.”  In 2021, /APL/ itself is only legally
available for subscribers or for people who purchase a paper copy of
the book. (Or through a library!)  Of course, like many famous texts
it can also be obtained extra-legally for download as a PDF: but that
format does not afford downstream users the opportunity to collaborate
on the text’s further development.

Gabriel and Goldman talk about sharing and gift culture in their essay
[[https://dreamsongs.com/MobSoftware.html][Mob Software: The Erotic Life of Code]].[fn:: Notably, this essay was
presented as a keynote talk at the same programming conference where
Alexander had delivered his keynote, cite:alexander1999a, four years previously.]  This reference suggests
another reason why sharing knowledge in non-editable can be
problematic.  Their primary source on gift culture is Hyde
cite:hyde2019gift, who talks about what happens when exchange items
are taken out of the gift exchange culture and puts in a museum:

#+begin_quote
A commodity is truly “used up” when it is sold because nothing about
the exchange assures its return.  The visiting sea captain may pay
handsomely for a Kula necklace, but because the sale removes it from
the circle, it wastes it, no matter the price.  Gifts that remain
gifts can support an affluence of satisfaction, even without numerical
abundance. (/ibid./, Chapter 1, p. 29)
#+end_quote

Gabriel and Goldman reference the open source community—but not the
free software community, so we will follow their usage here—as the
origin of Mob Software.

#+begin_quote
Because the open source proposition asked the crucial first question,
I include it in what I am calling “mob software,” but mob software
goes way beyond what open source is up to today. cite:gabriel2000mob
#+end_quote

That question is: “What if what once was scarce is now abundant?”  It
is well known that the PLoP conference series builds on this idea: it
includes shepherding and workshops cite:gabriel2002a as well as games,
informal gifts, and other measures that aim to create a sense of
psychological safety: all features that make PLoP a space where
‘failure’ is OK and even celebrated, as per Mob Software.  The essay
develops its own criticisms of open source, e.g., “the open-source
community is extremely conservative” and forking happens rarely.
(Five years later, with the creation of Git, forking became more
typical.)  Resonating with Tidwell’s critique from above:

#+begin_quote
One difference between open source and mob software is that open
source topoi are technological while mob software topoi are people
centered.
#+end_quote

On a technical basis, Gabriel’s vision sounds a lot like today’s world
of /microservices/.
While his vision hasn’t fully come to pass—for example there are still many
services with proprietary source code—nowadays many big companies
are also big proponents of open source.  Here we can notice that
Gabriel was employing a technique of imagining [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND
FUTURES]], e.g., he imagined a future in which:

#+begin_quote
Mentoring circles and other forms of workshop are the mainstay of
software development education. There are hundreds of millions of
programmers.
#+end_quote

We would like to dig somewhat deeper into the foundations of the
worldview that Gabriel puts forth in this essay. Usefully, an article
by VanDrunen “traces the source of Gabriel’s ideas by examining the
authorities he cites and how he uses them and evaluates their validity
on their own terms” cite:vandrunenchristian.  VanDrunen’s critique functions
as a (detailed) [[DECONSTRUCTION][DECONSTRUCTION]] of the thinking behind Gabriel’s essay.
Some key excerpts appear in Table [[tabone]].  

#+NAME: tabone
#+CAPTION: Key observations from VanDrunen’s critique of Gabriel’s “Mob Software” essay
#+ATTR_LATEX: :environment longtable :align |p{\textwidth}|  :label tabone
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| “Kauffman’s work is about a rediscovery of the sacred, and it amounts to a proposal of the laws of self-organization as a new deity”                                                                                                                  |
| “One thing we find in common with Lewis Thomas’s ants, Kauffman’s autocatalytic sets of proteins, and the agents inhabiting Sugarscape is that they all lack intelligence.”                                                                           |
| “In other words, the rules given by Gabriel describe only the conforming aspect of group behavior. In reality, there is a tension between independent and conforming tendencies, and the flock patterns emerge from the interaction between the two.” |
| “His examples of ‘mob activity’... the making of the Oxford English Dictionary, cathedral-building, and open source software discussed later—all had oversight, master-planning of some sort.”                                                        |
| “There are several distinct senses of ‘gift’ that lie behind these ideas, but common to each of them is the notation that a gift is a thing we do not get by our own efforts.” [Quoting Hyde cite:hyde2019gift.] |
| “Certainly proprietary code is shared property among those working in a corporate development team, but it is not common to the larger community of software developers and users.”                                                                   |
| “A computer program is not like a poem or a dance in this way; if the programmer is not able to produce something parsable in the programming language or cannot fit the instructions together in a logical way, the program simply will not work.”   |
| “Gabriel’s own experience may color his perception. He founded a software company that produced programs for Lisp development and which went bankrupt after 10 years.”                                                                                |
| “Moreover, if Gabriel means to suggest that these programming languages or models could have made programming more accessible to the masses lacking technical skill, it is quite a dubious claim”                                                    |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

It is worth noting that this is by no means a complete critique.  As
an an example of one direction that we will not have time and space to
develop here, some applications of the concept of ‘gift culture’ have
been criticised as hegemonic in nature cite:Mallard2019: should we
expect pattern-theoretic, mob, or free/libre/open source software
culture to be immune from such concerns?  VanDrunen’s criticisms are
useful for our purposes not because they provide the last word, but
because they points to the importance of considering the deeper layers
in developing a concept or approach.  There may also be conflicts at
these deeper layers.

It is also worth noting that mob software is but one of many diverse
visions of the future of programming cite:postmodernProgramming.  An
embrace of diverse perspectives seems to be a fundamental part of the
associated worldview.  After all, the
primary theoretical model of a computer is termed "universal".
Perhaps there is a bit of a paradox or double bind here, insofar as we embrace diverse
perspectives just as long as they are compatible with our core tenets.
For at least some pattern authors, these include “their love of programs
and programming” (/ibid./).  (On this last point, both VanDrunen and Gabriel
seem to agree.)


** Myths: metaphors and narratives (longer term change)

Lastly, there are *myths or metaphors* (e.g., Alexander’s idea that the
architect’s work is done ‘for the glory of God’ (see Galle
cite:GALLE2020345) or his conception that ‘primitive’ dwellings
contain more life).  To emphasize, CLA does not dismiss myths in the
slightest: on the contrary, they are what drive the other layers.
Another term that is used to characterise this layer is *narratives*.
VanDrunen surfaced various concepts in Gabriel’s essay that would be
at home at this level, for example, the concept of duende that Gabriel
takes over from Garcia Lorca originally derives from /dueño de casa/,
the name of a certain kind of household spirit.  However, myth here
does not just refer to such entities, but to the most deeply held
beliefs and concepts that underlie worldviews.

One important narrative for the pattern discourse is in plain view
within the terminology of problems and solutions, which come from
mathematics and physics.  Alexander worked /at the level of narrative/
to connect the patterns discourse to a scientific worldview, seeking a
sense of objectivity.  For example, in “The Atoms of Environmental
Structure”:

#+begin_quote
most designers ... say that the environment cannot be right or wrong
in any objective sense but that it can only be judged according to
criteria, or goals, or policies, or values, which have themselves been
arbitrarily chosen.  We believe this point of view is mistaken.
#+end_quote

Notice that, here, the discourse is positioned as different from the
mainstream of architecture.  The key differentiator is not the
language of problems and solutions, which would be familiar to anyone
with an engineering background; rather, but in a certain notion of
/wholeness/.  Which notion of wholeness remains to be surfaced.
Quoting, again, from “The Atoms of Environmental Structure”, we get
some relevant background:

#+begin_quote
We believe that all values can be replaced by one basic value:
everything desirable in life can be described in terms of freedom of
people’s underlying tendencies. ... The environment should give free
rein to all tendencies; conflicts between people’s tendencies must be
eliminated.
#+end_quote

Historically, there are at least two major varieties of wholeness: one
that is based on progressive differentiation (e.g., unfolding from
substance, per Spinoza), and the other generated by interaction
between components (e.g., mutually reflecting monads, per Leibniz).
In support of these allusions, a quote of Alexander from /The Nature of
Order/ (/TNO/): it “may be best if we redefine the concept of God in a
way that is more directly linked to the concept of ‘the whole.’”
\begin{echo}This sounds a lot like Spinoza!\endnote{We can obtain some useful \hyperref[DISTANCE]{DISTANCE} by thinking about how different kinds
of wholeness are associated with different symbols. In terms of
metaphors, we have already encountered overt images like that of
Chartres cathedral.  If we allow ourselves to explore further afield,
other symbols of wholeness come to mind: these include the circle, the
cross—or potentially the cross inside a circle,
\begingroup\alch\symbol{"3B}\endgroup.
Related but more
elaborated symbols include the circle with a cross rising above it
(\varTerra) which is both the modern astronomical symbol for Earth and
also linked with the Carthusian order, and the Rod of Asclepius
(\Asclepius, for the deity associated with healing or making whole)—this last symbol sometimes being inter-confused with the Caduceus
(\Caduceus, the symbol of Hermes, the deity associated with mediation
of various forms, and also echoed in the planetary symbol for Mercury,
\begingroup\alch\symbol{"53}\endgroup).}
\end{echo}
Indeed, the pattern discourse appears to draw from /both/ major traditions of wholeness, while also
seeking to unite them.  We get the idea of unfolding in /APL/ and other
pattern languages that work in a top-down manner: however, we also get
the notion of patterns and principles that are generative of emergent
phenomena.

At this level, architecture and programming were seen, by Alexander
cite:alexander1999a, to unite: his questions for the computer
scientists to whom he was speaking point in the direction of
bio-hacking and nanotechnology (e.g., for molecular self-assembly)—at least at the allusive level.  The following quote suggests we have
embarked on a fruitful track by attempting to think at the deeper
layers of the pattern discourse:
#+begin_quote
Generative patterns work indirectly; they work on the underlying
structure of a problem (which may not be manifest in the problem)
rather than attacking the problem directly.[fn:: https://wiki.c2.com/?GenerativePattern]
#+end_quote

\begin{echo}
Clearly, another key metaphor—which also has a
generative aspect—is the metaphor of \emph{language}.\endnote{“... as
in the case of natural languages, the pattern language is
generative. It not only tells us the rules of arrangement, but shows
us how to construct arrangements - as many as we want - which satisfy
the rules.”—\url{https://wiki.c2.com/?GenerativePattern}, quoting from
\emph{The Timeless Way Of Building}, pp. 185-6.}
\end{echo}
The prominence of linguistic metaphors within DPL reminds us that
Alexander’s architectural oeuvre contains many traces of symbols associated
with Hermes: a deity associated with communication and mediation.
Through these reflections we gain some useful [[DISTANCE][DISTANCE]].
#+begin_quote
In the house, [Hermes’] place is at the door, protecting the
threshold... He could be found around city gates, intersections, state
borders, and tombs (the gateways to the other world). cite:benvenuto1993hermes
#+end_quote
At the time when Hermes was actively embraced as a deity, in some
traditions he was paired with Hestia, the goddess of the hearth, whose
“domain was internal, the closed, the fixed, the inward” (/ibid./, here
and in quotes later in this paragraph).  The discourse around patterns
contains some aspects that move towards foundations (e.g., in the form
of fundamental principles, per /TNO/).  Such foundations could be
associated with Hestia, whereas Hermes would be on the side of
generativity and mutation.  The dichotomy seems to repeat itself
within the /TNO/ principles themselves: recalling that "focus" is the Latin
term for the hearth, Strong Centers would align with Hestia, whereas
Hermes would align more with Deep Interlock and Ambiguity.  The
resolution of the two forces within pattern language—as a form—seems be a variation of these Nietzschean lines: “anything that is
becoming returns” (i.e., is discussable as pattern), and, “contingency
resolves itself into necessity” (i.e., the wholeness of generativity
ultimately recovers the wholeness of unfolding).

\begin{echo}
Our task in this section has been to situate Alexander’s thought
relative to the myths and symbols of wholeness; we’ve surfaced some of
the tensions and dynamics that exist at this level.  Relationships to some
other contemporary thinkers are discussed by Elsheshtawy \cite{Elsheshtawy2001},
in particular, a relationship to Piaget’s conception of operational wholeness is developed.
Alexander, for his part, professed ignorance of French Structuralist theory (quoted at \emph{ibid.})—in particular, of Barthes and Foucault, whom Inayatullah draws upon—and he tags Nietzsche
as a nihilist, while distinguishing his own work
as comparatively hopeful \cite{alexander1991perspectives}. For further
reflections on Nietzsche and wholeness, see \cite{bishop2020holistic}.
For more on Hestia and Hermes in an architectural
context, see \cite{springhestia}.
\end{echo}

** Summary
A benefit of this deep dive into DPL via CLA is that we have gained
some new perspectives on how design patterns work.  In particular, we
have illustrated the complexity that underpins the model.  The concept
of patterns is simultaneously pragmatic and metaphysical in nature.
Alexander expands on the latter themes in /TNO/.  What we’ve seen above
is how these more ephemeral-seeming factors are ramified across
various layers of organisation.  For example, the theme of /openness/
can now be related to openness /to/:
- /criticism/ (Dawes and Ostwald cite:dawes2017a),
- /interpretation/ (Dawes and Ostwald again cite:Dawes2018)
- /failure/ (Gabriel cite:gabriel2002a), as well as to physical forms of
- /permeability/ (Alexander of /APL/ and the Greek god Hermes cite:benvenuto1993hermes).

We can expand this point and use it to illustrate what such an
analysis can potentially enable; specifically, we are interested in
CLA as a way to bring together different communities.  For example,
ERG and PLoP are both projects within the larger system of
contemporary computing, which is organised with various loose
hierarchical structures.  As such, both projects inherit attributes
from the larger communities/networks and histories to which they are
heirs. For example, ERG is a small subcommunity of the larger Emacs
community, and thus inherits two core tenets at the /worldview/ level:

- A preference for Free/Libre/Open-Source Software, as defined by the “four freedoms”.[fn:: https://www.gnu.org/philosophy/free-sw.en.html#four-freedoms]
- Enthusiasm for the features and affordances of Emacs, an extensible, customizable, and self-documenting editor cite:Stallman1981.

Both of these points have their origins in the worldviews and myths of
the hacker culture, in which Stallman, Steele and Gabriel all
participated.  As we saw above, at the worldview level, FLOSS is
sometimes linked with the concepts of a “gift economy”
cite:raymond1999cathedral and the theory of “self-organized emergence” /à
la/ Kauffman.  Whereas Stallman, Steele, and Gabriel come primarily
from the functional programming background, Ward Cunningham comes from
the Object Oriented (OO) programming subcommunity: these different
communities were not always in direct contact.  The =c2= pattern wiki
was primarily linked with OO traditions.  There, “openness” is a key
value at the worldview level: as we observed, the emphasis was on /in
situ/ editability and community effort.  With Emacs, the emphasis is
both on the availability of source code and the right to reuse it.  A
third perspective on openness comes from Gene Demby and Ashe Dryden,
who, along with others, have pointed out that the open source
community may not be so open, in practical terms, to newcomers from
all genders and ethnic backgrounds.[fn:: https://www.npr.org/sections/codeswitch/2013/12/05/248791579/why-isnt-open-source-a-gateway-for-coders-of-color][fn:: https://www.ashedryden.com/blog/the-ethics-of-unpaid-labor-and-the-oss-community] 

Bringing these perspectives together affords a more comprehensive
understanding of the concept of openness, along with its relationship
to other linked concepts like freedom, rights, and ethics; from this
basis we can explore dialectic tensions, and potentially initiate
dialogue.  “Openness” is but one of the themes appeared in the
CLA of the DPL literature and practices.  Various themes weaving
between the layers have been drawn out, informing the following
discussion.

# Nietzsche 's Fundamental Metaphysical Position, By Martin Heidegger,
# Translated by David Farrell Krell, Nietzsche, Volume Two, Chapter
# 26, pp. 198-208

* Discussion
<<Discussion>>

# \begin{echo}
# \begin{flushright}
# \emph{tl;dr: We consider how the methods described earlier could be used to address climate change adaptation.}
# \end{flushright}
# \end{echo}

We now have in hand a case study of the Emacs Research Group that
uses the [[PLACARD][PLACARD]] pattern as a unified whole, together with a deep dive
into design patterns more broadly, via CLA.  Here we would like to
reflect on why putting the CLA and DPL methods together can make a big
difference in practical terms.  To do this, we begin by examining a
specific problem domain to which CLA and DPL have been applied
separately.

Anthropogenic climate change is a situation of major global concern in
the early 21st Century.  It comes as no surprise that it has been
examined separately by proponents of both CLA and DPL.  We use this
recent history to frame future work building on the case study and
analysis developed above.

In an overview of their work on the Cooling the Commons pattern language, Cameron Tonkinwise and Abby Mellick Lopes write:
#+begin_quote
A design pattern is first an observation: “People in that kind of designed situation tend to do this sort of thing”. It is then possible to design an intervention that redirects those tendencies. If that intervention succeeds, it can become a recommended pattern to help other designers: “If you encounter this kind of situation, try to make these kinds of interventions” cite:theconversation2021.
#+end_quote
They amplify the ‘ethical’ aspect of their thinking:
#+begin_quote
... the patterns we are talking about, context-specific interactions
between people and things, are more like habits. They are tendencies
that lead to repeated actions.
#+end_quote
The 41 patterns they have developed include examples like \textsc{The Night-Time Commons},[fn:: https://www.coolingthecommons.com/pattern%20deck/]
which:
#+begin_quote
... might shift daytime activities into cooler night times.  Some
places already have these patterns: night markets and night-time use
of outdoor spaces.  If locally adapted versions of these patterns
encourage people to adopt new habits, other patterns will be needed.
These will include, for example, ways to remind those cooling off
outdoors in the evening that others might be trying to sleep with
their naturally ventilating windows open.  Such interlinked patterns
point to the way pattern thinking moves from the big scale to the
small.
#+end_quote
Reading this, we were concerned that, while the Cooling the Commons
patterns do acknowledge “horizontal complexity”—namely, through
interlinked patterns—the process does not deal with the “vertical
complexity” coming from the fact that diurnal rhythms are deeply
embedded in biology and culture.  People have cultural beliefs about
the activities that are appropriate for different times of day.
Public and domestic rituals are organized about the daily cycle.
Times of day have symbolic associations.  As far as we could tell,
these authors focused on more or less technical issues at the systems
level, and did not acknowledge these issues at the worldview and myth
levels.  A more comprehensive approach might, for instance, re-examine
rituals to see which of them relate to the phenomenon of sunrise
versus the act of getting up and starting the day, and then figuring
out how to adapt these rituals to a new schedule.  A suitable research
strategy might be to study how practices changed in the past, as with the
introduction of industrialization and its clockwork regimentation of
the day.

Meanwhile, Heinonen and coauthors cite:HEINONEN2017101 describe a CLA game that explored four
different scenarios in small groups.  The four scenarios were “Radical
Startups”, “Value-Driven Techemoths”, “Green DIY Engineers” and “New
Consciousness”.  As groups worked through the CLA for each scenario,
they developed a range of new ideas.  How would these CLA-linked
reflections have collated
with the patterns developed by Tonkinwise and Lopes and colleagues?
Might players have spotted ways in which the patterns would conflict
with deeper values—or ways in which they might be exploited to cause
chaos in the city cite:friction2016a?

Broadening our exploration of how design patterns relate to futures
studies, we should mention Schwartz cite:schwartz1996a (Appendix,
pp. 241-248), /viz./, his “Steps to Developing Scenarios”.  This process
follows an outline with a striking similarity to a design pattern
template.  Both Alexander and Schwartz advocate the identification of
driving forces in a context.  However, unlike Alexander, Schwartz does
not intend to resolve conflicts between the forces within a
harmonising design.  On the contrary, the aim in the scenario
development method is to understand how these forces might evolve and
lead to diverse scenarios.  We think that design patterns can be
useful inside scenarios, and also used to scaffold the design and
evolution of scenarios.

With these reflections in mind, here are four scenarios that will be
of interest to DPL practitioners, roughly pegged to the four layers of
CLA.  We should emphasise that these scenarios are not mutually
exclusive.

** Scenario I. Patterns become explicitly computational.
Patterns have been discussed in explicitly computational
terms—however, that direction of work so far remains mostly at the
level of a proposal cite:alexander1999a,moran1971a, with only limited
discipline-specific uptake (e.g., cite:jacobus2009a,
cite:OXMAN1994141, cite:taibi2003formal).  Could this change, to
generalise the kinds of patterns that can be computed with, and make
them interoperable?  Polya had already been writing about patterns of
plausible inference cite:polya1954plausible the year that Alexander
started his undergraduate degree in Cambridge;  four years later
Polya’s student Allen Newell was thinking about how to model the
inference process computationally cite:newell1958.  More recent work looks at how to
extract descriptions of Ostrom-style institutions from text
cite:Rice2021: such institutions are closely linked with design
patterns cite:ostrom2009a (p. 11).  Could this line of work be
extended, so that other kinds of design patterns could be recognised
where they appear?  Could the extracted descriptions be used directly
in computations?  One fruitful strategy might be to think of design
patterns as conceptual blends cite:Corneli2018, which can be given a
computational interpretation cite:SCHORLEMMER2021118.  For example,
the Cooling the Commons pattern language includes
\textsc{Community Library} as one of its patterns; the pattern blends a learning space
with cool refuge, and must balance these provisions against cost and
effort.  If the library was additionally blended with a
\textsc{Writers Workshop}, it could become a place for the community
to generate knowledge about new adaptive strategies.  However, this
might conflict with the notion of library contents as being read-only,
or with the view that libraries should be silent study spaces.  Could
these ideas and complexities be reasoned about computationally?

** Scenario II. Pattern language authoring communities move to free/libre/open source licensing.
# Let’s explore!

In the field of policy, /resilience/ describes a society’s
ability to recover after a shock; whereas /adaptive capacity/ describes
its ability to move to a new state cite:thonicke2020advancing,magnan2010better.
This ability is, in turn, linked with the health and adaptivity of the society’s
institutions cite:fidelman2017institutions.  Free/Libre/Open Source licensing is
one possible institutional innovation in the way design patterns are used that could
support social learning, in turn, boost adaptive capacity cite:THIHONGPHUONG20171.
As an example of work heading in this direction, Mehaffy and coauthors collaborated with Ward
Cunningham to make their book /A New Pattern Language for Growing
Regions/ cite:mehaffy2020new into a wiki, [[http://npl.wiki][npl.wiki]], which is licensed
under CC BY-SA 4.0.  Will other pattern developers follow suit and
move to open licensing—and suitable infrastructures for working with open contents?

# add refs to reproducible research papers
# add refs to Minnesota 2050 paper
# Maybe add a comment saying these people were ‘sort of’ working together (in different rooms)

** Scenario III. PLACARD scaffolds new literacies of collaboration.

As we’ve seen in our work with Emacs and Peeragogy (and previously
with the online community PlanetMath cite:krowne2003,corneli-thesis) projects need more
than simply access to source code in order to thrive.  We see a link
to the topic of reproducible research.  Above and beyond the immediate
technical considerations cite:sandve2013ten, the process of doing
science is “reproducible” if the methods are teachable to others.  The
Literate Programming paradigm can be useful for this.[fn:: For notes on doing reproducible research with Emacs, see https://emacsnyc.org/2014/11/03/org-mode-for-reproducible-research.html]
  At the same time, collaboration
across different skill sets is challenging.  One reason we need
additional scaffolding might be familiar to the protagonists of our
pizza story: “Innovation foils attempts to be consistent and
efficient” cite:tan2020uncertainty (p. 12).  Adapting to climate
change won’t work if we only do business as usual.  In the Minnesota
2050 project, participants were selected from a variety of professions
and leadership roles to produce scenarios for energy and land use, and
combined modelling with scenario planning cite:olabisi2010.  However,
actually solving large-scale problems together in interdisciplinary
teams will require new thinking and additional tools: to bridge
between the viewpoints of, e.g., professional futurists, programmers,
data scientists, local farmers—and to draw on the insights of
citizen scientists cite:wildschut2017a.

** Scenario IV. Patterns eat Big Tech.
Reflecting on the increasingly contextual and transdisciplinary nature
of the discussions at PLoP and other venues, along with the other
points above, brings to mind Hesse’s /The Glass Bead Game/.  For those
who are familiar with the novel, this reference could also suggest:
proceed with caution.  How hierarchical do we want our community, or
our society, to be?  How much are we in touch with practical realities?  How critical are we capable of being towards the
tenets we hold dear?  When reflecting on futures-oriented discourses,
Slaughter described a spectrum: “participatory and open at one pole
and closed (or professionalised) at the other” cite:SLAUGHTER1989447.
Access to meaningful participation is a serious question in our
current technological culture cite:unger2019knowledge.  Does our
experience of unequal access reappear in the future cultures we
envision?  With due care, patterns might become the basis of
widespread technical literacies, not only for an elite group of hackers or
for a few highly-paid rockstars, but for everyone.

# maybe reference the Bloom’s 2 Sigma problem here
# Only half of the students will make it to the end of the course and only half of those get A’s

** Summary
#                                                                   Need to recap Alexander 1999 at some point
Our vision for change—now speaking as part of the design pattern
community—is that the four scenarios we described above will be given
serious thought.  Progress will become measurable through markers of
debate and dialogue between the different communities whose work we have
drawn upon, and perhaps through ensuing trial-and-error uptake or
adaptation of the methods we’ve described.  Appendix [[flaws-appendix]]
contains a workshop proposal that we will submit to PLoP 2021
alongside this paper.  In the workshop we hope to explore the biome
of concepts and techniques that can help to build adaptivity in
groups.  If the workshop goes well, it could be repeated around with
changes to explore other topics, such as food security, or, indeed,
the future of design patterns.

* Related work
<<Related_Work>>


We are certainly not the only people to think about systems and
futures: what is distinctive about this paper is that we’ve connected
these domains with the design pattern terminology and methods.  The
individual methods we described have various analogies (e.g., between
PAR and AAR, or \textsc{Daily Scrum}, as noted above; one could also
point to Architectural Decision Records[fn:: https://adr.github.io/]
and other review tools).  The work as a whole has some analogies with
a method called Causal Layered Synthesis developed by Paul Wildman
cite:wildman2010engaging. Seamon cite:seamon2019christopher develops an
analysis of Chrisopher Alexander’s work with some parallels to our
analysis of DPL via CLA.  

# At the broadest philosophical level, Simondon cite:simondon2009technical provides a detailed analysis of the technical mentality, which can help to frame pattern methods.

To further our understanding, we begin this section by engaging
potential criticisms.  Some prominent critical voices have been
introduced above.  To recapitulate, Dawes and Ostwald provided a
comprehensive view of criticisms of DPL; Tidwell questioned the
non-user-centredness of much DPL discourse; VanDrunen focused on
potential friction or incompatibilities at the worldview level between
mob software and other cultures; Demby and Dryden explain that the openness of FLOSS isn’t actually open to all in the same way by default.  We can broaden out somewhat further,
to reveal further tensions.

- Shaw and Hill cite:shaw2014 talk about how commons-based peer
  production is not necessarily egalitarian, so, even if DPL was to
  move to FLOSS model, we would expect to see cultural winners and
  losers.
- In a related critique, our collaborator Paola Ricaurte pointed out
  that an approach to peer production that centres European and North
  American designers, while ignoring local communities and
  relationships, is potentially just another form of rehashed
  colonialism.

To expand on this: our work takes a counterposition to Kostakis et
al. cite:kostakisDesignGlobalManufacture2015 who argued for a
development model based on “thinking global and producing local.”  At
the centre of their vision is a global pool of designs, which are put
into production in local Fab Lab facilities.  By contrast, the [[PLACARD][PLACARD]]
pattern centres local circumstances and histories (via PARs,
CLA-linked methods like [[GENEALOGY][GENEALOGY]], and the context-specific
information embedded in DPL).  We would expect to see varied knowledge
bases develop, that are rich with cultural diversity and human
relationships.  [[PLACARD][PLACARD]] methods could flip the Kostakis et
al. formula on its head: patterns are primarily tools for thinking
locally about particular contexts, individual relationships, conflicts
and circumstances; CLA puts them in context, and PAR keeps this system
up to date.  Only secondarily and potentially does this lead to any
shared global resource.  More likely, the methods we’ve described
would simply strengthen local forms of resilience and better identify
healthy futures.

#+BEGIN_EXPORT latex
\afterpage{\clearpage
\begin{figure}[h]
\begin{equation*}
  \xymatrix{
    \hbox{\textbf{context}} & \hbox{\textbf{form}} & \hbox{\phantom{mental picturexxx}} \\
    *+[F]{C1}  \ar@{<->}[r] & *+[F]{F1} &            \hbox{\hspace{-.2cm}actual world}}
\end{equation*}
\vskip 10pt
\emph{\textbf{A.}~As a base case for creative work, there is a close relationship between content and form, and they evolve together. Alexander calls this unselfconscious: people do things by tradition, trial, and error, rather than by design.}
\vskip -20pt
\begin{equation*}
  \xymatrix{
    \hbox{\phantom{form}} & \hbox{\phantom{context}} & \hbox{\phantom{mental picture}} \\
    *+[F]{C1} \ar[d] & *+[F]{F1} & \hbox {actual world} \\
    *+[F]{C2}  \ar@{<->}[r] & *+[F]{F2} \ar[u] & \hbox {mental picture}}
\end{equation*}
\vskip 10pt
\emph{\textbf{B.}~Here, we add a mental picture that abstracts from the context (e.g., design requirements) and the form (e.g., plans).  In short, now work takes place mediated by a design process.  This allows specialisation of labour, but there’s no longer a direct unmediated link between $C1$ and $F1$.}
\vskip -20pt
\begin{equation*}
  \xymatrix{
    \hbox{\phantom{form}} & \hbox{\phantom{context}} & \hbox{\phantom{mental picture}} \\
    *+[F]{C1} \ar[d] & *+[F]{F1} & \hbox {actual world} \\
    *+[F]{C2} \ar[d] & *+[F]{F2} \ar[u] & \hbox{mental picture} \\    
    *+[F]{C3}  \ar@{<->}[r] & *+[F]{F3} \ar[u] & \hbox {formal picture}}
\end{equation*}
\vskip 10pt
\emph{\textbf{C.}~Now we add a meta-language: the formal picture (e.g., a pattern language) corresponding to the mental picture.}
\vskip 10pt
\begin{center}
\begin{minipage}[c]{0.45\textwidth}
\begin{equation*}
  \xymatrix @C 5pt @R 6pt {
    & \ar@2{->}[d]
      & & & \t \ar@{-}[lld] \ar@{-}[rdd]  \ar@{-}[rrrdd] & & & & \\
    & & \t \ar@{-}[ld] \ar@{-}[rdd] & & & & & & \\
    & \t \ar@{-}[ld] \ar@{-}[d] \ar@{-}[rd] & & & & \t
      \ar@{-}[ld] \ar@{-}[d] \ar@{-}[rd] & & \t \ar@{-}[d] \ar@{-}[rd] & \\
  \t & \t & \t & \t & \t & \t & \t & \t & \t}
\end{equation*}
Program, consisting of sets, based on an analysis
\end{minipage}
\hskip 25pt
\begin{minipage}[c]{0.45\textwidth}
\begin{equation*}
  \xymatrix @C 5pt @R 6pt {
    & & & & \T \ar@{-}[lld] \ar@{-}[rdd]  \ar@{-}[rrrdd] & & & & \\
    & & \T \ar@{-}[ld] \ar@{-}[rdd] & & & & & \ar@2{->}[u] & \\
    & \T \ar@{-}[ld] \ar@{-}[d] \ar@{-}[rd] & & & & \T
     \ar@{-}[ld] \ar@{-}[d] \ar@{-}[rd] & & \T \ar@{-}[d] \ar@{-}[rd] & \\
  \T & \T & \T & \T & \T & \T & \T & \T & \T}
\end{equation*}
Realization, consisting of diagrams, a synthesis
\end{minipage}
\vskip 10pt
\emph{\textbf{D.}~At this level we have methods for actually doing the programming.}
\vskip 10pt
\end{center}
\caption{Diagrams from \emph{Synthesis of Form}\label{synthesis-diagrams}}
\end{figure}
\clearpage
}
#+END_EXPORT


That leads to our next point, which is to briefly examine how
this work relates to an agenda developed by
Christopher Alexander himself.  We can begin by drawing the reader's
attention to two diagrams from Alexander's /Notes on the Synthesis of
Form/ (/NSF/) recopied here as Figure \ref{synthesis-diagrams}.  Parts
A.-C. of this figure have two columns corresponding to “context” and
“form” (i.e., the latter being analogous to what we have been calling
a /solution/ in this paper).  These component figures have one, two, or
three rows, with labels “actual world”, “mental picture” and “formal
picture”.  A creative problem is posed at the level of the /actual
world/, say, “build a house atop this hill” or “make a celebration song”.

The problem can, however, be addressed at any one of the three levels.  The most
direct approach is to work in the actual world.  For instance, a
musician might pick up an instrument, start playing something, try out
different possibilities, modify notes or phrasings to make it sound
better, and so come up with a song.

At the level of /mental picture/, a designer receives design
requirements which describe the problem, and produces a plan which
describes a solution.  For instance, the host of the party might make
a request “Write a joyous song for alto voice accompanied by flute and
trumpet to celebrate the acceptance of our paper into the conference.”
A composer might then sit down at a desk, away from any instruments,
and write out a score which would later be handed to the singer and
instrumentalists for performance.  Alexander points out that there is a
danger in this process: the composer would no longer have the
immediate feedback which comes from working directly in the actual
world.  Accordingly, the result might be a song that matches the
description, but doesn’t match the mood of the event.

Alexander’s proposed solution is to produce a /formal picture/ of the
mental picture, and instead work with that formal picture.  For our
example, this might take the form of a suitably elaborate music theory,
one that includes concepts like  ‘\emph{ballabile}’ (to indicate that
the song should be danceable).  More generally, we employ a suitable
metalanguage to reason about the mental representation; this process
of reasoning can then take the place of feedback from the actual world
in guiding and evaluating our designs.  In /NSF/ this consists
of a set-theoretic formalization of design requirements and potential
misfits.\endnote{Incidentally: why only three rows here?  According to G\"odel, any language that can count can also serve as its own metalanguage.}

Figure \ref{synthesis-diagrams}D. refers to the process of design once
we have arrived at the "formal picture" level.  The left panel
represents the analytic process in which one decomposes a design
problem into subproblems and the right panel represents the
complementary synthetic process in which one successively combines
solutions to subproblems to arrive at a solution to the original
problem.  In /NSF/, Alexander proposed a maximum entropy method for
carrying out the analysis and, in later works, introduced design
patterns for use in the synthesis; and ultimately, described 15
principles that could guide a design at an even more abstract level.

As we move from the actual world to the formal picture, the content of
the mental process becomes more detached from the context and is more
widely shareable among a community who is conversant with the formal
language.  There are trade-offs involved: the shared formal language
may not always capture the intricacy of local relationships.  In this
paper, we have considered the problems faced by groups of people
organizing their activities.  The naive “actual world” approach
(Figure \ref{synthesis-diagrams}A.) would be when a group takes a
"seat of the pants" approach to dealing with issues as they come up in
the course of work.  PAR can help to sketch a “mental picture”.  CLA
and DPL can then be used to formulate a “formal picture”, as in our
Case Study, where we moved from informal PARs, via a CLA, to next
steps linked with patterns.  Once this has been done, we arrive at a
stage where we can use DPL to synthesise solutions, much as Alexander
envisioned, returning to the other methods as needed.

Thanks to CLA, we have also gained a further understanding of some
meta-level issues that can arise when applying DPL.  Our analysis
and scenarios point to a range of social and cultural issues—like
varied notions of openness, the complex relationship between diversity
and hierarchy, the tensions between innovation and efficiency, and the
interaction of formal and informal reasoning—which can round
out the already well-recognised “concerns for pedagogy, efficiency,
flexibility, and convincing argument” cite:postmodernProgramming
embraced by pattern authors.  Just as even a talented musician without
a solid grasp of music theory would be hard pressed to compose an
augmentation canon or symphony, so too we suggest that a group which
faces complex challenges may want to consider the meta-level issues
that can be addressed with [[PLACARD][PLACARD]] when orchestrating their
activities.  In sum, the methods we’ve discussed can be used to
operationalise a strategy that is at the heart of Christopher
Alexander’s oeuvre.  In future work it would be interesting to look
further at how this relates to programs- and programming-specific
design considerations, as described, e.g., by Felleisen et
al. cite:felleisen2018design.

* Conclusion
<<Conclusion>>

In 1999, the architect Christopher Alexander discussed the future of
design patterns with an audience of programmers.  We revisited
this topic, aided by a method from the field of future studies.  We
developed a practical case study, an analysis of the design pattern
discourse, as well as several scenarios that members of the design
pattern community might wish to consider as they give shape to this
community’s future development.

We began by thinking about patterns from a fundamental perspective.
Some patterns repeat in space, some in time, some in both space and
time; think of a tiling, a beat, a wave.  However, patterns cannot
repeat exactly: their elements are subject to spatial or temporal
displacement, and other forms of variation.  We need suitable
abilities—and methods—to perceive and work with patterns.  The methods
we used in the paper were the Project Action Review (PAR), Causal
Layered Analysis (CLA), and Design Pattern Languages (DPL)—though
other methods that fulfill the same basic purpose could be used
without significantly changing the overall import of what we say here.
- By using the PAR (or another sensory method), we are able to identify recurring themes.
- Then, by using the CLA (or another cognitive method), we are able to organise these repeating themes in a structure that exposes the underlying trends, causes, and potential terminating states.
- With DPL (or another motor method) we can make what we have learned actionable.
The methods can be interwoven, as we illustrated by combining PAR, CLA, and DPL into the [[PLACARD][PLACARD]] pattern.

# ¶¶¶ This reference to other methods isn’t gratuitous; what other ways are out there?  Can we find and study them?

In our case study, we have seen that the combination of PARs and CLAs
can be used as methods to create a rough plan.  Adding connections
from this developing plan to an existing DPL further strengthened our
work, not least by connecting it to a broader community.  We have
used [[PLACARD][PLACARD]] as a way to integrate perspectives from people with
different backgrounds.  The constituent methods themselves are sourced
from different communities, and we believe that [[PLACARD][PLACARD]] may be useful
for bringing these communities together, which could help their
work become more robust.

We can imagine these methods being readily applied in workshop
settings. For example, if we were to gather a group of citizens,
experts, and other stakeholders to talk together about the city, they
could use the methods we’ve described to surface issues, rehash
concerns, and sensemake together.  “Anticipatory Social Science” is a
broader term for this kind of work.  Working with methods that
distribute perception, cognition, and action, we may become more comfortable
with uncertainty, and better able to support innovation.  Especially when we
think about contemporary problems like climate change, it is not
enough to think about the past; ultimately, we need to develop a
transformative set of tools and methods cite:miller2018transforming; 
and beyond this, a coherent worldview, and even new myths.
Citizen science has a potentially important role to play here
cite:wildschut2017a, and the methods described could help to support
widespread engagement.

Our paper reflects on several domains in which design patterns have
been used.  Alongside the broader transdisciplinary contribution, we have
started to develop a set of requirements for software that can help people work with these methods.  As Turing said about the
future, we can see plenty there that needs to be done.  Lastly, as
regards Alexander’s visionary question: perhaps the ‘Chartres of
programming’ has been hidden in plain view all along.  Alejandro
Jodorowsky refers to the Marseilles Tarot as a “nomadic cathedral”
\cite{jodorowsky2009way} (p. 10); it seems to us that pattern languages
are very much the same sort of thing.

# \begin{quote}
# So too, bhikkhus, I saw the ancient path, the ancient road travelled
# by the Perfectly Enlightened Ones of the past. And what is that
# ancient path, that ancient road? It is just this Noble Eightfold Path;
# \end{quote}

* Acknowledgements
:PROPERTIES:
:UNNUMBERED: t
:END:

We thank our PLoP 2021 shepherd Michael Mehaffy for supportive
comments and productive discussion.  This manuscript is distantly
derived from submissions to the Connected Learning Summit 2018,
Anticipation 2019, and the /Futures/ journal.  We thank the coauthors
and reviewers of these earlier submissions for helping to shape our
thinking here.  We thank Claire van Rhyn for bringing the Anticipation
conference to our attention and thereby introducing us to the field of
futures studies and CLA.  We acknowledge the comments and
participation in online seminar discussions of: Paola Ricaurte, Roland
Legrand, Lisa Snow MacDonald, Verena Roberts, Charles Blass, Stephan
Kreutzer, Giuliana Marques, Cris Gherhes, Qiantan Hong, Cameron Ray
Smith, David O’Toole, and Rebecca Raper.

\appendix
* NOTES :noexport:
\printendnotes*[sverre]
* APPENDIX: Example PAR: Emacs Research Group, December 2, 2020
<<appendix-pars>>

The Emacs Research Group maintained a practice of carrying out a PAR
at the end of each meeting.[fn:: Data archived at
[[https://github.com/exp2exp/exp2exp.github.io]].] This is the first of
those PARs.

<<exemplar-par>>
#+BEGIN_EXPORT latex
\begin{enumerate}
\item \textbf{Review the intention: what do we expect to learn or make together?}
\begin{itemize}
\item Joe Noorah and Leo wanted to convene a meeting with interested parties in Emacs+Research
\item Address longstanding worry about “wait until next year”
\item Part of a greater sense of trying to do something with EmacsConf to federate the community
\end{itemize}
\item \textbf{Establish what is happening: what and how are we learning?}
\begin{itemize}
\item Met for an initial 70 minute meeting (via Zoom)
\item Everyone shared a brief intro and ideas so we got to know each other
\item Joe took notes via screenshare... we all took notes (as academics)
\end{itemize}
\item \textbf{What are some different perspectives on what’s happening?}
\begin{itemize}
\item Cameron: We are meeting for the first time so there’s a lot of intro information
\item We generally agreed that we want to make something that exposes intrinsic value of using these tools
\item Vaguely agreed on follow-up directions, this seems to be a general consensus, often with full agreement (e.g., on testing and making a collaborative Org Roam work, to further cement as tool for collective thinking in combination w/ individual)
\item David: there are ways I could help out with extra elisp, helping figure out a package, intro elisp workshop
\item Joe: Leo did an amazing job facilitating the meeting
\item Ray: I was impressed by the diversity of the group in background \& levels of use
\end{itemize}
\item \textbf{What did we learn or change?}
\begin{itemize}
\item We can do this!
\item We feel empowered
\item Wonderful outcome from attending EmacsConf 2020!
\item Public Policy conference: (How to get a grant?)
\end{itemize}
\item \textbf{What else should we change going forward?}
\begin{itemize}
\item Ongoing dialogue
\item Maybe with breakout groups
\item Need for governance for this; getting public, taking time we need going forward
\item Many actions need to be taken forward but we have too many right now: maybe this should be the next objective to pick a good viable project to go after now
\item Can set up a shared Org Roam + Firn instance: do we want to use this?
\item Can work have something similar w/in Org Roam
\item Someone to schedule the next meeting... accomodate UTC+8, maybe use BBB; Leo will publish scheduler
\end{itemize}
\end{enumerate}
#+END_export

** PAR: Emacs Research Group, February 13, 2021 :noexport:
<<exemplar-par-2>>
*** 1. Review the intention: what do we expect to learn or make together?
**** We all met one another!
**** Leo: ‘I’d set out to take good notes from this meeting because it was something that I’d been expecting for a while, and I haven’t been disappointed by the quality of the exchanges we’ve been having’
*** 2. Establish what is happening: what and how are we learning?
**** Last time, we had a special guest: Qiantan
**** We’re continuing on the path of interdisciplinary learning
**** We might have also convinced Qiantan of joining us with HyperReal!
**** Ray has already been working with Peeragogy, especially on the topic of /patterns/
*** 3. What are some different perspectives on what’s happening?
**** Power dynamics (especially power to your house… Re: power-cut when taking those notes)
*** 4. What did we learn or change?
**** We talked about /hyper-notebooks/ in terms of the replicability/reproducibility of research
**** Anthropology + Psychology is a special nightmare for reproducibility
*** 5. What else should we change going forward?
**** We’ve brainstormed a couple of options for /getting out there/: White-papers, Grants, Journal papers (very concrete)
**** Could there be a joint ERG/org-mode venture with the Peeragogy podcast?
**** Once Charlie is brought up to speed, he could have a discussion with Leo
**** Potential interview with Leo & Jethro Kuan (co-maintainers of org-roam)
**** This could get us working on patterns!
**** The patterns of maintenance
**** Charlie thinks it’d be interesting to dig further on the topic of AI as a peer, patterns, and Peeragogy
**** Joe mentions that the Peeragogy Handbook only lists 9 patterns
**** Maybe the ERG could contribute further patterns?

** PAR: Emacs Research Group, April 17, 2021: Special guest session :noexport:
<<exemplar-par-3>>
*** 1. Review the intention: what do we expect to learn or make together?
**** Alex learn some Emacs paradigms
**** Others help and demo different Emacs ideas
*** 2. Establish what is happening: what and how are we learning?
**** Started with what Alex is most familiar with: vim and PowerShell (and RStudio, unshown)
**** Helpful to go over /what Emacs is/ rather than just showing the detail
**** Plurimodel approach, between ‘lay perspective of how do I do who I do elsewhere’ 
**** Getting the wireframe
**** Demos in Emacs Lisp, Clojure, and R—we could do Javascript or whatever
**** evil mode
*** 3. What are some different perspectives on what’s happening?
**** We could use these patterns with others
**** Noorah would be interested in a more detailed discussion
**** Cameron has a similar background and became a fan of Doom
**** “if you don’t like the default, that’s OK, the E stands for Extensible”
**** Alex’s perspective: I thought you’d ask me. Learning Emacs as someone who never used Emacs or Lisp before is hard. But, when you can talk to people and get a feedback loop going, then it comes into its own. Documentation exists but it’s learning a new language. Let alone the keybindings. But if I listen to you talking, I hear the important stuff. 
**** Docs are more intended as reference
**** “What is the specific command to do this”—it would be like trying to learn a language with a dictionary and grammar book
**** Alex agrees with Leo’s playground perspective: I know what to do in another setting... but not here!
**** Emacs is so much more than the text editor
**** Text-interface?
*** 4. What did we learn or change?
**** You don’t learn a language by looking at a dictionary (unless you’re a linguist and a bit crazy)
**** But there’s a problem with Emacs, which is that there isn’t proper intro
**** Combined many years of suffering learning the ropes.
**** We’re trying to do here: doing what we would have liked to have had; and having more people onboard.
**** Both vim and Emacs are awful for beginners, but people who use vim are already using the command line...
*** 5. What else should we change going forward?
**** We’re missing a proper tutorial introduction to Emacs
**** Human mediation between the documentation and what Emacs is ... is what allows you to apprehend the value of what Emacs is
**** If we had a good tutorial (we do have good docs)—the feeling of being guided by a human voice would be enough...
**** But there was no such guidance; you were in the middle of an alien playground.  “But I just wanted to do my Clojure stuff.”
**** Joe can guide: both how to do the Clojure stuff and how to do the high-level stuff, and how to learn the ropes more efficiently
**** Alex, please take notes on how you learn Emacs, and adopt a meta perspective. If you want to do something but you don’t know how to do it in Emacs, document it. Write a little about your experience—it will make it easier for us to help you, and help other people with their similar user stories. =#emacs-classroom=?

** PAR: Emacs Research Group, April 17, 2021: Full session :noexport:
<<exemplar-par-4>>
*** 1. Review the intention: what do we expect to learn or make together?
**** AM: My major intention was to meet you guys and learn something, wanting to reinforce existing knowledge of emacs and develop it further
**** RSP: In part 2 wanted to make progress with the layered analysis—to actually do it!—making some progress
*** 2. Establish what is happening: what and how are we learning?
**** Joe was given the keys to the car—though Leo did take them back
*** 3. What are some different perspectives on what’s happening?
**** Leo did a nice job of intervening
**** Missed Noorah and hope she and Alex will talk at some stage soon (e.g., about writing)
**** Missing David and Charlie; did they get the link?
**** Ray has serious commitments in bio—now catching up with the Easter stuff
*** 4. What did we learn or change?
**** I think we got a better sense of CLA and a new use case
**** Alex’s schedule is busy in 2 weeks, though has finished up some classwork freeing up time
*** 5. What else should we change going forward?
**** We should go back and read some Inyatullah papers
**** We are developing our intention to do something with group writing even if we haven’t figured out
**** Alex is welcome any time, and note we can do in a spotlight session, either on Saturday (2hr) or 1600 (circa *20 minutes*)
**** I think we should probably be thinking more in terms of PAR+CLA for Hyperreal?

** PAR: Coauthors of Patterns of Patterns, July, 2021 :noexport:
<<second-exemplar-par>>

#+BEGIN_EXPORT latex
\textbf{1. Review the intention: what do we expect to learn or make together?}
\begin{itemize}
\item Our intention was to apply the CLA method from future studies to
design pattern theory, in order to provide a methodologically
salient perspective on the future of pattern theory.
\item Within the Emacs Research Group, we used PARs, CLA, and DPL to
manage our work, and we shared a description that process and its
results as a case study here.
\item And to make sense of how these things connect with each other—practically, to show how causal layered analysis could work
synergistically with pattern theory.
\item To get practice using PARs and CLA as frameworks to support our
learning and thinking about patterns of patterns, we also used these
methodologies in other concurrent project
\end{itemize}
\textbf{2. Establish what is happening: what and how are we learning?}
\begin{itemize}
\item We introduced our methods and illustrative case study, then took a
deep dive into patterns.
\item We connected our observations with some broader literature on future
studies and proposed scenarios describing ways in which design
patterns might evolve.
\item We used these methodologies to learn more about and reflect on our
working methods at large: we improved out meta-methodological
capacity in this regard.
\end{itemize}
\textbf{3. What are some different perspectives on what’s happening?}
\begin{itemize}
\item JC:\footnote{Viewpoints contributed by authors, listed here by first and last initials. This could be seen as somewhat analogous to a CRediT (Contributor Roles Taxonomy) statement, but rather than saying what roles people filled, it talks about their view on the paper at present.} The patterns and futures communities need to be talking to each other!
\item RP: One of our goals with the paper was to make the connection
between futures and patterns.  We could have discussed earlier some
scenarios for the paper, like “what if it doesn’t get published?”
We could have had a meeting way back in May or June where we looked
at scenarios.  We could take the scenarios above and use them to
start building out a set of further scenarios for Emacs Research
Group, peeragogy, and so on.
\item LV: I’m glad everyone is on board in reviewing the paper. The
diverse views of contributors provides some wealth because people
are discovering things in different ways.  We’ve nicely modularised
the pattern of reviewing a paper, and brought different gazes that
can only lead to more wealth and appreciation.
\item NA: Hi folx I'm still a bit disoriented with the jet lag, enjoy the
break and see y'all in August!
\item CD: Keep in mind that these are patterns people but not CLA people
(by default): we should make sure that we have presented CLA in a
way that they grasp.
\item AM@CD: I'm sure patterns people are very clever cookies anyway. Are
we patterns people? If we try to imitate their language too much—might we say something silly?
\item VB: It starts to make more sense: patterns become recognisable
patterns, we understand the paths we did, we can better understand
the steps that we will do.  We developed methods that can be
repeated and upgraded.  Our familiarity with working with methods
helped us in our work; and clarity in methods will help us welcome
newcomers.  We can pitch to people about this.  We’re complex
people; as we open to each other we can better be open to others.
\item AM@VB: Welcoming for newcomers—nice! I agree, it's easy to use
these methods (I certainly managed it)!
\item CP: \emph{Fearless Change} is related work in connection with the futures
stuff.  You need things like this as projects develop over time to
understand what’s going on.  I feel more access to this paper than
our previous writing topics on this topic.
\end{itemize}
\textbf{4. What did we learn or change?}
\begin{itemize}
\item Relative to earier attempts to describe patterns to the futures
community, this work is more mature.
\item It is a fitting third installation to round out Joe’s “Patterns”
trilogy \cite{corneli2015a,Corneli2018}.
\item Our methods are compatible with the ideas described by Christopher
Alexander, and a lot more detail about how these methods can be
applied to the activities of an organisation.
\item There’s a whole behind the scenes, there’s a lot of heart and soul
here that could make it more like joint autobiography.
\end{itemize}
\textbf{5. What else should we change going forward?}
\begin{itemize}
\item We believe we have an answer to Alexander’s question.  We’re not
sure he’ll like it.  The ‘Chartres of programming’ has been hidden
in plain view all along.  Alejandro Jodorowsky refers to the
Marseilles Tarot as a “nomadic cathedral” \cite{jodorowsky2009way}
(p. 10); pattern languages are very much the same sort of thing.
This is a project of many lifetimes of work; let’s understand it
better so that we can coordinate in parallel.  Let’s make sure we
get relevant material in front of the people who need to see it, in
a form that they can engage with, with the aim of building community
in varied contexts.
\item Since we have approached writing this paper in a transdisciplinary
manner, rather than as experts, there will be more here for all of
us to learn.  Shall we perhaps structure our work on the paper
differently in the next phase?  At the moment, the organisation has
been mostly ad-hoc and organic.  As part of our reflection on
methods, we've talked about things like the pomodoro technique:
maybe we don’t want to be that strict, but at minimum we will likely
want to do more to figure out scheduling with the many authors.
\end{itemize}
#+END_export

* APPENDIX: Patterns
<<appendix>>

[[DECONSTRUCTION]]-[[REORDERING KNOWLEDGE]] are direct adaptations of Inayattulah’s Poststructural Futures Toolkit cite:inayatullah1998b to the pattern format.  [[FORMAL PATTERNS]]-[[DIVERSITY]] elaborate new patterns surfaced by ERG for inclusion in the Peeragogy Handbook.  The patterns are referred to within the text using all-caps.
** DECONSTRUCTION
<<DECONSTRUCTION>>

- *Context*: A text: here meaning anything that can be critiqued—a movie, a book, a worldview, a person—something or someone that can be read.  (/NB./, every text has a /context/: much like every pattern has a context.)
- *Problem*: The existence of a ‘text’ suggests a *conflict* between (1) the notion of truth embedded in that text, and (2) the text itself as historically situated or positioned within relationships of power.
- *Solution*: We break apart the text’s components, asking what is visible and what is invisible? Who or what is privileged within or by the text? Which assumptions does the text make preferable?  How is ‘truth’ produced within the text?  Who is silenced?  In this way, we ‘deconstruct’ the universality of the text and show its contingent nature.

# LV: It feels like this is full-circle back to Sapir-Whorf where the language you speak frames how you think... if language is supposed to be the trace of our cognition, and have an input on how you think—the way we use or modify idioms is telling of how culture manifests itself into language & language manifests into cognition.

#+BEGIN_COMMENT
\noindent
*Example* The technique of _deconstruction_ examines how a
text is constructed and often does this by evoking the contingencies and potential
arbitrariness of symbols in language.  In
our pizza example, we have the book on running a business.  When the couple
revisited it critically, they noted some peculiarities of the language.
For instance, the book routinely divided people into winners and
losers, even in contexts which had nothing much to do with
competition.  The upshot of this was that the couple came away with
the impression that the language of the book, the way it talks about social
organisation, and the way it itself organized
the material embodied a worldview at odds with their values.  By
seeking advice in this book indiscriminately, they were unwittingly
following the implicit worldview, leading to frustration
and confusion.
#+END_COMMENT

** GENEALOGY
<<GENEALOGY>>

- *Context*: History is not just the passage of time, but an unfolding of different positions. We consider a /concept/ or /idea/ to be historically situated in this sense.
- *Problem*: Within history, certain discourses have been hegemonic. A given term or concept will have developed through varied discourses: this observation *conflicts* with a naive notion of terms or concepts as simply ‘given’ or universally true.
- *Solution*: One takes a word or concept, looks at the way it
  has been understood and interpreted in different eras, and
  how these different understandings came about.  We ask: which
  discourses have been victorious in constituting the present?
  How have they travelled through history? What have been the
  points in which the issues have become important or
  contentious?  By tracing the evolution of a given term or
  concept through periods of identity or sameness, and through
  periods of difference or divergence, we come face-to-face
  with its generative potential.

#+BEGIN_COMMENT
\noindent
*Example*   On a personal
scale, we have Mom's notion of "restaurant".  When she was small, a
restaurant was a magical place where her family would go on special
occasions.  When she grew up, a restaurant was a place to socialize
with friends and meet new people.  Lately, it has been synonymous with
balance sheets, market share, supply chains, and customer
satisfaction.  She wonders how such a thorough change happened
so fast and whether she could recover some aspects of the earlier
understandings into the current context.
#+END_COMMENT

** DISTANCE
<<DISTANCE>>

- *Context*: The present.
- *Problem*: The present seems ‘normal’, but this *conflicts* with any impetus to change.
- *Solution*: We ask: which scenarios make the present remarkable?  Make it unfamiliar? Denaturalize it?  Where are these scenarios, e.g., are they in historical space—the futures that could have been—or in present or future space? By establishing a sense of distance from the present, we can return to explore the present from a different point of view.  We are more likely to see the ever-changing character of the present, points of leverage, and how to use them.

#+BEGIN_COMMENT
\noindent
*Example* As long as our couple was in the thick
of things, running the shop and fixing one problem after another, they
couldn't really see what was going on, only feel uneasy.  In order to
interpret their situation, they needed to create some mental space by
bringing in other possibilities.  After a conversation where they
explored other restaurants they had known, recalled how things were in
the past, thought of ways they thought things might have gone better
or worse but didn't, they returned to the current situation and found
themselves noticing all sorts of things which hitherto they had been
taking for granted.
#+end_COMMENT

** ALTERNATIVE PASTS AND FUTURES
<<ALTERNATIVE PASTS AND FUTURES>>

- *Context*: The past that we see as truth is in fact the particular writing of history: it is a text amenable to [[DECONSTRUCTION][DECONSTRUCTION]].  The futures that we are ‘given’ are, similarly, only some of the ones that are in-principle-possible due to the evolutionary nature of concepts exposed by their [[GENEALOGY][GENEALOGY]].
- *Problem*: The past and future are put to use within discourse, resulting in some winners and some losers.  The results we see may *conflict* with our sense of what we would prefer to have happen.
- *Solution*: With this technique, one notes how and why some
  interpretations of the past and visions of the future have
  been promoted whilst others have been suppressed. We ask:
  which interpretation of the past is valorized?  What histories
  make the present problematic?  Which vision of the future is
  used to maintain the present?  Alternatively, which visions
  undo the unity of the present?

#+BEGIN_COMMENT
\medskip
\noindent
*Example*  Based upon his
daily readings of old-time New Englanders, Pop realizes that the view
of history as an inexorably steady march of economic and technical
progress leaves a lot out of the picture.  If so much was left out of
our recall of the past, what aspects of the present are being ignored and
what potential futures are being dismissed?  This line of questioning inspires
Pop to rethink the restaurant as a modern-day Walden cabin in which they
commune with nature for one half of the week and commune with their
neighbors for the other half of the week.
#+end_COMMENT

** REORDERING KNOWLEDGE
<<REORDERING KNOWLEDGE>>
- *Context*: Trends and problems are emergent, historical, and political: they are embedded in complex webs of becoming.
- *Problem*: It’s not always obvious how to move /between/ the ‘layers’ mentioned above. This *conflicts* with any given effort to empower oneself with a deeper understanding of the situation.
- *Solution*: We ask: how does the ordering of knowledge differ across civilization, gender and episteme? What or Who is othered? How does it denaturalize current orderings, making them peculiar instead of universal? What tools can we use to reorder knowledge, to make it available in new forms without necessarily requiring the same historical baggage?

#+BEGIN_COMMENT
\noindent
*Example*
In the technique of _reordering knowledge_, one asks what principles
have been used to organize knowledge, what are the implications to
this, and what are alternatives.  In rereading their books, our couple
notes that they are organized about a framework of impersonal market
forces.  This reinforces a dog-eat-dog view of the world which, in
turn, rationalizes profiteering and hypercompetition.  Thus, the
couple decides to re-organize the patterns for running a business in a
people-centric manner where markets are but one type of social
institution amongst many.
#+end_COMMENT

** FORMAL PATTERNS
<<FORMAL PATTERNS>>

- *Context*: Working with project- and change-management
  \textsc{Technologies} across a distributed \textsc{Community}.
- *Problem*: Using patterns, todo items, CLA, and PARs in an intuitive
  manner is clearly workable at a small scale, but could become
  chaotic when we scale up; this *conflicts* with our perspective that
  these methods can be applied broadly.
- *Solution*: Can we develop a more mathematically precise way to
  describe this set of tools?  We might build on the earlier work of
  Corneli et al. cite:Corneli2018 which describes patterns as
  /conceptual blends/.

#+BEGIN_COMMENT
\noindent
*Example*
Let’s add some examples with reference to the world of free/libre/open source software?
#+end_COMMENT

** SERENDIPITY
<<SERENDIPITY>>
- *Context*: Within an ongoing research and development project.
- *Problem*: The idea of planning *conflicts* with our experience that
  reliance on plans can produce rigid behaviour and a corresponding
  brittleness.
- *Solution*: We adapt our plans to increase our /general/ preparedness, and adapt our strategy to decrease our reliance on accurate /forecasting/. This operationalises the ‘serendipity pattern’ described by Merton.[fn:: “The serendipity pattern refers to the fairly common experience of observing an unanticipated, anomalous and strategic datum which becomes the occasion for developing a new theory or for extending an existing theory… ” cite:merton1948bearing, reprinted in cite:merton.]

#+BEGIN_COMMENT
\noindent
*Example*
Let’s add some examples with reference to the world of open source?
#+end_COMMENT

** RECOMMENDER
<<RECOMMENDER>>
- *Context*: Within our use of \textsc{Technologies} and materials we
  could \textsc{Reduce, reuse, recycle}.
- *Problem*: As the body of content grows, it can be harder to find
  relevant material or the best collaborators in a global pool: this
  *conflicts* with our desire to achieve excellence.
- *Solution*: New software that can help surface relevant material and
  opportunities would be useful.  Existing implementations include
  “scrobbling” audio tracks to Last.fm, or buying recommended products
  on Amazon.  The same ideas can be adapted to FLOSS, research,
  learning, and other domains.

#+BEGIN_COMMENT
\noindent
*Example*
Let’s add some examples with reference to the world of free/libre/open source software?
#+end_COMMENT

** DIVERSITY
<<DIVERSITY>>
- *Context*: Within a \textsc{Project}.
- *Problem*: If we only collaborate within a relatively homogeneous
  population of people who think like us this *conflicts* with our
  desire to find new ideas and new solutions, and to do widely relevant work.
- *Solution*: Look out for different contexts in which we can   collaborate with different people; they don’t all have to work on   the same project.  We recognise that collaboration is easier when we   share similar languages and literacies.  In cases where   collaboration needs to be made tighter, prefer ways of exchanging   information and expertise with \textsc{Newcomers} that makes the   relationship one of peers rather than a one-way hierarchy.  Understand the historical landscape through techniques like [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND FUTURES]]. At the same time, by inviting people who were not closely connected or emotionally invested in your   project, you can get the advantages of [[DISTANCE][DISTANCE]], at least vicariously.  Diversity may be absent for contingent historical reasons, rather than as a design principle, e.g., within   free software only about 5% of the participants are female, whereas   women occupy around 25% of computing occupations cite:Vedres2019.
#+BEGIN_COMMENT
\noindent *Example* Let’s add some examples with reference to the world
of free/libre/open source software?
#+end_COMMENT

* APPENDIX: Flaws of the Cool City workshop
<<flaws-appendix>>

Our workshop explores the interaction between Design Pattern Languages
and Causal Layered Analysis (CLA) in the context of a cooperative game.
It also introduces attendees to these methods, assuming no previous
background.  The theme of the workshop is amelioration of and adaptation
to climate change in an urban setting.  Since cities account for more than
70% of global CO2 emissions, the workshop will help participants engage
with a crucial challenge of our time.

The workshop will combine material from several existing sources:

- Neo-Carbon Energy Scenarios cite:heinonenradical,heinonen2017a,heinonen2017neo
- Cooling the Commons cite:cooling2021
- Flaws of the Smart City cite:friction2018
- Causal Layered Analysis cite:inayatullah1998b

CLA is a research methodology for examining a topic of concern and
forming a plan of response that takes into account different kinds of
causes, ranging from immediate events to deep-seated cultural beliefs.
CLA has previously been applied in a workshop setting to analyse the four
neo-carbon scenarios: “Radical Startups”, “Value-Driven Techemoths”,
“Green DIY Engineers”, and “New Consciousness”.  To make
these scenarios tangible to participants, we will draw on existing published
descriptions of earlier workshops.

In our workshop we will then explore the scenarios further by using
*Cooling* cards, based on the 41 patterns from the Cooling the Commons
pattern language.  We will use the interactive game Flaws of the Smart
City to structure game play.

** Training phase.
:PROPERTIES:
:UNNUMBERED: t
:END:

The workshop involves different roles, and participants will be
briefed on these roles in separate groups, along with a short general
introduction.  The four roles are linked with the four resources
mentioned above:

- *Historian* (briefed on the Neo-Carbon Energy Scenarios)
- *Designer* (briefed on the Cooling the Commons cards and pattern methods)
- *Kaijū Communicator* (briefed on Flaws of the Smart City)
- *Analyst* (briefed on CLA)

Players will be asked to define their role via the four CLA layers of
/litany/, /system/, /worldview/, and /myth/.

In the general introduction we will give this example: the Cooling the
Commons pattern language includes the pattern
\textsc{The Night-Time Commons}.  This pattern proposes to move many daytime activities to the night. 
If we examine this pattern via CLA, we can see some potential problems:

- Litany :: The concern arises that diurnal rhythms are deeply embedded in biology and culture: waking up at a non-standard time could be difficult for many people, interrupting their habits and their coordination with other people.
- System ::  People have cultural beliefs about the activities that are appropriate for different times of day.
- Worldview :: Public and domestic rituals are organized about the daily cycle.  People may have self-identity views of who they are relative to clock time, like “early bird gets the worm”.
- Myth :: Times of day have symbolic associations.

** Part one.
:PROPERTIES:
:UNNUMBERED: t
:END:

We will divide participants into four groups (or fewer; so long as
there are at least four persons per group, representing the four roles).
Each group will be embedded within a scenario. Basic game play will be roughly
as per Flaws of the Smart City: a turn consists of a randomised selection of a *Rule*,
*Action*, *Place*, and *Issue* card. Following the selected *Rule* (e.g., to
play as an Evil Genius or Guardian Angel), participants will discuss
how the *Cooling* cards can be employed to disrupt or enhance the city.
At the end of each turn, participants will be asked to align the
*Action*, *Place*, *Issue*, and selected *Cooling* card(s) with the four layers
of the CLA. Participants will be asked to annotate each layer, and
in addition, make note of any adapted, related, or new design patterns that would be
relevant at each level. They will additionally be asked to make note
of how these selected cards fit into the scenario’s historical
development.

** Part two.
:PROPERTIES:
:UNNUMBERED: t
:END:

The resulting tableaux will then be shared back with the larger group
in a short presentation.

** Part three.
:PROPERTIES:
:UNNUMBERED: t
:END:

In the third phase, participants will be remixed from across the four
scenarios and roles, and will be invited to work in these new groups
to reflect on the scenarios and develop a Project Action Review (in
the pre-PAR formulation, see below) to describe something that they
would, concretely, like to work on in the future, either in their
professional networks, or in their local communities.

1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?

** References :noexport:

S. Heinonen, M. Minkkinen, J. Karjalainen, and S. Inayatullah. Testing transformative energy scenarios through causal layered
analysis gaming. Technological Forecasting and Social Change 124 (2017), 101–113. https://doi.org/10.1016/j.techfore.2016.10.011

Sirkka Heinonen, Noora Vähäkari, and Joni Karjalainen. Neo-Carbon Energy World; What Opportunities for Chile. Neo-Carbon Energy Futures Clinique IV (2017).

S. Inayatullah. 1998. Poststructuralism as method. Futures 30, 8 (1998), 815–829. DOI:http://dx.doi.org/10.1016/S0016-3287(98)00086-X

Cameron Tonkinwise and Abby Mellick Lopes. Cooling the Commons. (2021). https://www.coolingthecommons.com/pattern%20deck/

* The end                                                           :ignore:

#+begin_export latex
\bibliographystyle{ACM-Reference-Format-Journals}
\bibliography{./main}
#+end_export

\clearpage

* OUTTAKES :noexport:

# #+INCLUDE: "first-par.tex" export latex

** Methodological contribution
:PROPERTIES:
:UNNUMBERED: t
:END:
PARs are related to patterns, in that they describe a context, and
surface problems and solutions that arise or are likely to arise in
that context.  They might be seen as a template for proto-patterns.
However, they do not necessarily have a strong repeating aspect.  CLA
could be seen to play the opposite role to PARs.  Metaphorically, CLA
integrates the tangent vectors that characterise the observations we
have gathered as we work together, and can be used to reconstruct the
shared meaning of our work.  DPL, then, can turn this understanding
into practical high-level plans.  By contextualising DPL with the
other methods, we avoid brittle solutions and enrich our thinking.

** Constructively critical contribution
:PROPERTIES:
:UNNUMBERED: t
:END:
If the ideas and methods we have examined were actively used and
improved jointly by all of the different communities whose work we
have drawn on, many things could start to move quickly.
- The Emacs Research Group can use these ideas to help connect with potential stakeholders.
- The Peeragogy network can help facilitate some of the discussions and projects.
- PLoP can provide relevant social infrastructure and connections with others using pattern methods.
- As we gather further evidence, we can return to the futures community and share what we learned with them, and expand the scale and scope of the integrated effort.


** Fundamental definition of patterns
:PROPERTIES:
:UNNUMBERED: t
:END:

Let’s begin by setting to one side any specialist notion of ‘patterns’
that we may have in mind, and think about patterns in a fundamental
way.  Some patterns repeat in /space/, some in /time/, some in both /space
and time/—a tiling, a beat, a wave.  In the physical world, it would
seem that patterns cannot repeat exactly, or forever.  The elements
that comprise a pattern are subject to spatial or temporal
displacement, and other forms of variation.

Let’s now explore the notion of ‘design pattern’ starting from this
foundation.  Leitner supplied the following summary: "[Design]
Patterns are shared as complete methodic descriptions intended for
practical use by experts and non-experts" \citep{leitner2015a}.  As we
look into the matter further, two central features emerge.  

** Outline of implications 
:PROPERTIES:
:UNNUMBERED: t
:END:

# US Army—Steve Blank
# Download entrepreneurship patterns for Vitor

In our Discussion we draw out implications for the future of
design patterns.  We look briefly at how DPLs and CLA have been
applied (separately) to discuss the problem of anthropogenic climate
change.  We suggest that the integrated strategy we propose here could lead
to more satisfactory outcomes on problems of this scale.  We then
develop four scenarios for the possible future development of
pattern-theoretic methods.  In the section on Related Work, we engage
with further critical views, along with similar techniques that have
been applied in the various communities who developed the methods we
are studying, with a focus on Alexander’s /Synthesis of Form/.  By way of Conclusion, we present a PAR for the paper as a
whole.  This is offered as an example of a potential best-practice for
pattern authors, on the view that widespread adoption of this method
would help improve collaboration within the design patterns community.

** Epilogue sourced from Virgina Woolf.

\begin{quote}
\emph{It is only by putting {\upshape[the shock]} into words that I make it whole; this wholeness
means that it has lost its power to hurt me; it gives me, perhaps because by doing
so I take away the pain, a great delight to put the severed parts together.}  [...]
\emph{From this I reach what I might call a philosophy; at any rate it is a constant
idea of mine; that behind the cotton wool is hidden a pattern; that we—I mean all
human beings—are connected with this; that the whole world is a work of art;
that we are parts of the work of art.}
\end{quote}


** summary erg


Looking back over the case study, we can now outline an answer to the
concern raised at the end of Section [[methods]], namely how do the
[[PLACARD][PLACARD]] methods help, concretely, to develop solutions?  Let’s begin
by revisiting the notion of patterns from a fundamental perspective.
Patterns are something that repeat.  Some patterns repeat in space,
some in time, some in both space and time; think of a tiling, a beat,
a wave.  In the physical world, it would seem that patterns cannot
repeat exactly, or forever. Their elements are subject to spatial or
temporal displacement, and other forms of variation.  By using the PAR
or another sensory method, we are able to identify recurring themes.
Then, by using the CLA or some other cognitive method, we are able to
organise these repeating themes in a structure that exposes the
underlying trends, causes, and potential terminating states.

A useful analogy can be made with the notion of a macro or program.
Once we notice that we end up repeating the same gesture frequently,
we may then look for ways to automate it.  In order to do the
automation, we need a grasp of the relevant existing facilities.  With
Emacs, the most straightforward tasks can be automated by using
built-in commands, or by recording new keyboard macros.  Other tasks
are typically automated through new Lisp code, or with interfaces to
other programs.  Still more involved and less readily automated
solutions require working together with other people who have
different knowledge or facility with other tools.

Hello from joe


Broadly, a solution process can often be decomposed into interrelated
subtasks alexander1964notes,polya1945solve,polya1954plausible.  If we
are able to understand the (sub-)context and (sub-)problems in
detail—along with their relationships to other parts of the developing
decomposition—then we can then make predictions about the way an
intervention could change the overall system.  As we will revisit
again later on in the paper, there are “two different forms of
information processing (bottom-up and top-down)” cite:Teufel2020; CLA
can help with both, and in so doing can indeed assist with
solution-development.  Nominally, CLA is an analytic tool that
decomposes a problematic situation into /layers/, and /causes/ operating
at and between these layers.  In this sense it functions top-down.
However, CLA also plays a synthesis role.  Whereas we could compare
the PAR to a tangent vector or derivative that gives a momentary
reading of how things are going at a given point in time, CLA can be
used to integrate these observations into an overall plan—as we’ve
seen above.

** contentious point

That said, this line of thinking leads us to ask if there is a form of
hegemonic power lurking inside the methods we’ve described.  After
all, the notion of gift culture has been critiqued on that basis
cite:Mallard2019; would we expect pattern-theoretic or free software
culture to be exempt?  Furthermore, supposing that patterns (and
software) are indeed tools for liberating many human tendencies: is
that wholesome in every case?  And who decides?
Having raised these concerns we certainly will not reject them out of
hand, rather, we suggest that the philosophical and cultural issues
around patterns need further thought.  This underscores our broader
point that thinking about how patterns—and other methods—should be
done contextually.
