#+Title: PATTERNS OF PATTERNS
#+AUTHOR: É T A L E
#+Date: June 14th 2021
#+BIBLIOGRAPHY: /home/joe/pattern-reboot/main.bib
#+HTML_HEAD: <script src="https://hypothes.is/embed.js" async></script>
#+LATEX_HEADER: \usepackage[a4paper,bindingoffset=0.2in,left=1in,right=1in,top=1in,bottom=1in,footskip=.25in]{geometry}
#+LATEX_HEADER: \usepackage[table,dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage[math-style=french]{unicode-math}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \setmonofont[Color=blue]{Ubuntu Mono}
#+LATEX_HEADER: \newfontfamily{\alch}{Alchemy}
#+LATEX_HEADER: \newfontfamily{\mm}[Color=red]{DejaVu Sans Mono}
#+LATEX_HEADER: \setmainfont[BoldFont=EB Garamond,BoldFeatures={Color=ff0000}]{EB Garamond}
#+LATEX_HEADER: \newcommand{\hookuparrow}{\mathrel{\rotatebox[origin=c]{90}{$\hookrightarrow$}}}
#+LATEX_HEADER: \definecolor{pale}{HTML}{fffff8}
#+LATEX_HEADER: \definecolor{orgone}{HTML}{83a598}
#+LATEX_HEADER: \definecolor{orgtwo}{HTML}{fabd2f}
#+LATEX_HEADER: \definecolor{orgthree}{HTML}{d3869b}
#+LATEX_HEADER: \definecolor{orgfour}{HTML}{fb4933}
#+LATEX_HEADER: \definecolor{orgfive}{HTML}{b8bb26}
#+LATEX_HEADER: \definecolor{gruvbg}{HTML}{1d2021}
#+LATEX_HEADER: \newenvironment*{emptyenv}{}{}
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \sectionfont{\normalfont\color{red}\selectfont}
#+LATEX_HEADER: \subsectionfont{\normalfont\selectfont}
#+LATEX_HEADER: \paragraphfont{\normalfont\selectfont}
#+LATEX_HEADER: \subsubsectionfont{\normalfont\selectfont\color{black!50}}

* Abstract
We introduce Inayatullah’s Causal Layered Analysis method from the
field of futures studies into the domain of patterns.  We elaborate
some “CLA patterns” and apply them to think about the future of the
pattern theory.  We discuss our findings relative to other concrete
activities in linked collaborative research and development projects
that we are involved with.
* Introduction
Causal Layered Analysis is a technique developed by Sohail Inayatullah
in the field of future studies: we apply it here to provide a new
long-term perspective on design patterns.  We have found CLA useful in
other collaborative projects more broadly, and our analysis suggests that
it can be a useful adjunct to pattern methods.  Symmetrically, we think that
patterns could be useful in future studies applications.

Briefly, Inayatullah developed CLA — building on earlier work by
Slaughter cite:SLAUGHTER1989447 and a theoretical perspectives
developed by Foucault — because he perceived that many efforts in the
field of futures studies were often short on philosophical depth.  CLA
is used to understand a developing issue of concern by looking at it
across four layers of increasing depth, which are referred to as the
/litany/, /system/, /worldview/, and /myth/.

In somewhat dryer terms — which would be familiar within an
Aristotelian tradition — if we are interested in understanding /events/,
it is natural to look at the /causes/, the /deeper causes/, and the
/deepest causes/.  Alterantively, in mathematical language, if we are
curious about the evolution of a variable $x$, we may want to look at
its second, third, and fourth derivatives.  Once we have an
understanding of the issues of concern across these several layers, we
can be better informed about the way the issue will evolve in future.
Importantly, if we are interested in creating change, then we should
be careful to think about where to make an intervention.  CLA is used
for /analysis/, but Inayatullah also pairs it with CLS for /synthesis/ of
new strategies.

We can illustrate the issues with a short story.  Imagine a couple who
on their first few dates enjoy going out for pizza.  They like
different toppings: but that doesn’t matter, because each of them
orders their own perfectly sized Neopolitan-style pizza, and eats it
with gusto.  Indeed, it turns out they like pizza so much that they
would like to have it several nights a week.  Going out this
frequently would be expensive, so they get good at making their own
pizzas at home: selecting good ingredients, fermenting the dough, and
baking at a high temperature.  After some time goes by, they have
gotten really good at this, and they daydream about opening their own
restaurant.  They look into some available practical guidance and
adapt it for their use case cite:kelly2012business,wurm2019design.
After a lot of planning and a whole lot of work, they get their new
pizza restaurant up and running, and they are doing good business.
However, as more time goes by, they begin to notice some stress.
Why’s that?

Imagine that one of the two was excited to pursue a vision of
/self-reliance/, inspired by historical figures like Thoreau — whereas
the other partner was more focused on the /quality of the food and the
health of their relationship/, inspired by the contemporary Slow Food
movement, along with childhood memories of parents who loved cooking
together.  These days, our two protagonists hardly see each other any
more!  One of them is still around the restaurant every day, greeting
customers and baking — the other is off sourcing ingredients and
developing relationships with others in the local food supply chain.
If they realise that the challenges they face — alongside their
successes to date — are driven by different but reasonably compatible
values, it is likely that with due care the points of difference could
become mutually supportive.  Otherwise, there is a risk that our two
protagonists will end up at loggerheads.

Pattern languages often work across levels.  Nevertheless, there are
some additional techniques and perspectives to be gained from CLA;
furthermore, we think that patterns and futures work can be mutually
supportive.  After introducing our methods in more detail, we will
develop a Causal Layered Analysis of the patterns discourse, and then
discuss some of the implications for practice.
* Methods
<<methods>>
** Design Patterns
LET’S BEGIN by setting to one side any specialist notion of ‘patterns’
that we may have in mind, and think about patterns in a fundamental
way.  Some patterns repeat in /space/, some in /time/, some in both /space
and time/: a tiling, a beat, a wave.  In the physical world, it would
seem that patterns cannot repeat exactly, or forever.  The elements
that comprise a pattern are subject to spatial or temporal
displacement, and other forms of variation.

Let’s explore the notion of ‘design pattern’ starting from this
foundation.  Leitner supplied the following summary: "[Design]
Patterns are shared as complete methodic descriptions intended for
practical use by experts and non-experts" \citep{leitner2015a}.  As we
look into the matter further, two central features emerge.  Like an
ellipse, the concept of the design pattern has two main foci: context
and community.
# [fn:: An ellipse is the set of all points in a plane such that the sum of their distances from two fixed points is a constant.]

- /Context/ shapes and constrains the type of activity which is being considered, such as designing a building, or writing software.
- /Community/ encompasses the stakeholders --- experts and non-experts alike --- who are involved with or affected by a particular project.

Integral to the basic concept of a design pattern is a third feature
that describes the interaction of the community and the context.  The
community uses the pattern to overcome some real or potential /conflict/
that they experience within this context.  The conflict is also
referred to as a /problem/; its resolution is described a /solution/.

Alexander and Poyner emphasised that ‘design’ is not needed when the
conflict can be resolved in an obvious or straightforward manner.  For
example, you typically would not need a design process surrounding
/sitting in a chair/, because “under normal conditions each one of the
tendencies which arises in this situation can take care of itself”
\citep[p.~311]{alexander1970a}.

All of this means that design patterns need to achieve something
fairly subtle.  Each represents the synthesis of a repeatable solution
to a type of conflict which itself repeats within a particular
context.  Furthermore, it does this a way that makes the solution
teachable, learnable, and otherwise replicable within a given
community.  However, if the design pattern makes the solution to the
problem too obvious, then “design”, /per se/, is no longer needed![fn::
For example, Peter Norvig argued that we see fewer of the design
patterns typical of object oriented programs inside programs written
in functional and dynamic languages, because these languages embed
many of the typical patterns as language features.]  Accordingly, we
might say that the design pattern carries with it a fragment of
irreducible complexity.  This perspective may or may not be
surprising.

Alexander had described the need for patterns when things get complex
cite:alexander1964notes.  He specifically focuses on what could be
called “horizontal” complexity, a situation where there are a lot of
moving parts and relations between them.  Methodologically this is
elaborated with the notion of a /pattern language/.  Pattern languages
have a property of unfolding, from more general to more specific.
However, they seem to leave open deeper forms of “vertical”
complexity, where there are deep historical or ontogenetic causes, or
complex conceptual issues, which are not readily expressible in
design-pattern-theoretic terms.  Let’s have another look at these
issues by way of two contrasting metaphors.

The first metaphor comes from Christian Kohls, who proposed to treat
each design pattern as a journey: “a path as a solution to reach a
goal” cite:kohls2010a.  In this metaphor, design patterns are
understood to have an initial condition and an end condition, defined
within some context, which also defines a cost function on traversals
of paths.  There are two problems: the more elementary problem is to
traverse the terrain and travel from the start state to the end state
at low cost; the second problem is to find a reliably repeatable way
to do this.  Once found, the low-cost path can be described to and
traversed by others.

The second metaphor comes from Joseph Campbell, who described a kind
of “archetypal pattern” cite:shalloway2005a, one that can be found
embedded in myths and stories across diverse cultures and historical
periods.  The “hero’s journey” is also typically described with a path
cite:campbell1949a, however, in this case the path runs in a circle,
and focuses on the transformations of the hero who traverses it.
Although an account of the journey can be shared, traversal is
effectively presumed to be single-use.  The cost is typically “high.”
Nevertheless, once a myth or metaphor is established by way of a
shared narrative, the journey can be reenacted through ritual or
engaged with in other ways that solve a range of social problems
cite:handelman1998a.

This should suggest that Kohls’s metaphor does not fully express the
complexity that is underpins each design pattern.  It does hint at
this complexity, because it implies a regress: where we initially had
/one/ problem (traversal + low-cost), now we have one more (traversal +
low-cost + sharable).  The problem complex calls out for suitable
methods, and on this basis we should expect to find patterns for
finding, writing, and discussing patterns: and, of course, we do.
However, this material does not fully explain where design patterns
come from — or where they are going to — not an an obviously graspable
way.  To really get a handle on /the future of the pattern theory/
cite:alexander1999a, we need another approach.

** Causal Layered Analysis



We begin this section by using some of the familiar literature on
design patterns to briefly introduce Inayatullah’s
cite:inayatullah1998b,inayatullah2004causal Causal Layered Analysis
(CLA) formalism through an example: Table [[tabpatterns]]  is a quick initial
analysis of the patterns literature across the surface, social,
worldview, and myth layer.  We will look at related issues in much
more detail later.

This method is a good fit for the need identified in the previous
section, because CLA is typically used to answer the question: “What
is our vision for change and how is progress measurable?”  For
example, in Alexander’s cite:alexander1999a case, the vision was that
of “the generation of a living world” — but the process whereby
progress would be made was somewhat less clear.

To help make the CLA practicable as a /method/, we will now turn to five
techniques that Inayatullah refers to as the /poststructural futures
toolbox/.  Here, we treat them in the classical design pattern format.

#+NAME: tabpatterns
#+CAPTION: CLA introduced by example: a speed-through of the design patterns
#+ATTR_LATEX: :environment longtable :align |p{\textwidth}| 
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| The first layer in CLA is the *surface level*.  In the case of the design patterns discourse, this level includes, for example, the familiar kinds of patterns that are published in papers, discussed at PLoP, put into use in designs of various kinds, or debated by practitioners (e.g., Christopher Alexander’s “Entryway Transition” pattern, but also his remarks about how people who attempted to apply his methods ended up placing “alcoves everywhere”, etc.). This is sometimes also referred to as the *problem level*: in the patterns discourse, this is all very familar, because problems abound.  The other synonym for this layer is the *litany layer*: it describes the problems that everyone is familiar with. |
| Beyond that, we have the *social phenomena* that cause the problems to emerge — along with their solutions.  In the original setting in which patterns developed, this layer might include causes such as more people living in cities, combined with the possibility of developing a more community-driven approach to design.                                                                                                                                                                                                                                                                                                                                                                                                    |
| The next layer beyond that comprise *worldviews* (e.g., Alexander’s view that “There is a central quality which is the root criterion of life and spirit in a man, a town, a building, or a wilderness”).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Lastly, there are *myths or metaphors* (e.g., Alexander idea that the architect’s work is done ‘for the glory of God’ (see Galle, 2020) or his conception that ‘primitive’ dwellings contain more ‘life’).  To emphasize, CLA does not dismiss myths in the slightest: on the contrary, they are what are seen drive the other layers.  Another term that is used to characterise this layer is *narratives*.                                                                                                                                                                                                                                                                                                                        |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

*** DECONSTRUCTION
<<DECONSTRUCTION>>

- *Context*: A text: here meaning anything that can be critiqued — a movie, a book, a worldview, a person — something or someone that can be read.  (/NB/, every text has a /context/: much like every pattern has a context.)
- *Problem*: The existence of a ‘text’ suggests a *conflict* between (1) the notion of truth embedded in that text, and (2) the text itself as historically situated or positioned within relationships of power.
- *Solution*: We break apart the text’s components, asking what is visible and what is invisible? Who or what is privileged within or by the text? Which assuptions does the text make preferrable?  How is ‘truth’ produced within the text?  Who is silenced?  In this way, we ‘deconstruct’ the universality of the text and show how it is contingent.

# Example: ‘How did Howard’s interviews for Tools for Thought go?’
# If people talk about ‘freedom’ we can try to find the assumptions
# - "what is freedom" - well, not the 4 freedoms in the original version
# ... back when the Americans were fighting the british.
# - because of economics stuff... slavery made sense
# - but racism was their the lower causal layer!
# - At the economic layer it was making good sense

*** GENEALOGY
<<GENEALOGY>>

- *Context*: History is not just the passage of time, but an unfolding of different positions. We consider a /concept/ or /idea/ to be historically situated in this sense.
- *Problem*: Within history, certain discourses have been hegemonic. A given term or concept will have developed through varied discourses: this observation *conflicts* with a naive notion of terms or concepts as simply ‘given’ or universally true.
- *Solution*: We ask: which discourses have been victorious in constituting the present? How have they travelled through history? What have been the points in which the issues have become important or contentious?  By tracing the evolution of a given term or concept through periods of identity or sameness, and through periods of difference or divergence, we come face-to-face with its generative potential.

# EPISTEME: How does Foucault use this term?  It’s linked to TRUTH, with the theme below.  Briefly, we start with how we grasp knowledge, the fact that Foucault was considering truth to be relative, but it was ways to access the truth — at the time.  Ways to reach it.

# — This is interesting

# GENEALOGY: it’s about looking at the RAMIFICATION of an idea — what inspired it and what did it inspire.
# Putting it back in the topic of truth: rather than looking how the thing evolved, here’s interested in how a particular *ERA* dealt with the idea — something more horizontal.  Zeitgeist — ideas from the time.  It’s not just about tracking one idea from across that time, but more about getting a perspective of how the idea was applied by the people.  STOICS: Epictetus, Senica played with care of the self.  Even though there’s chronological movement.

# Archeology is centred on the present, drawing conclusions for the present.
# Genealogy: more like a petrie dish of today

# Example: update on Joe’s collaboration with Luís
# - instead of blending, you work back up the tree

# - Foucault started as archeologist;
# Paul Vin : classicist worked on Rome, recently translated Aeneid

*** DISTANCE
<<DISTANCE>>

- *Context*: The present.
- *Problem*: The present seems ‘normal’, but this *conflicts* with any impetus to change.
- *Solution*: We ask: which scenarios make the present remarkable?  Make it unfamiliar? Denaturalize it?  Where are these scenarios, e.g., are they in historical space — the futures that could have been — or in present or future space? By establishing a sense of distance from the present, we can return to explore the present from a different point of view.  We are more likely to see the ever-changing character of the present, points of leverage, and how to use them.

# Example: ‘Distance’ can show up in physical space, e.g., at UT Austin    the public affairs school is in a secluded area, in a park and a somewhat obscure library; the mathematics building is adjacent to “applied mathematics” but logic and metaphysics are housed in a different part of the campus.

*** ALTERNATIVE PASTS AND FUTURES
<<ALTERNATIVE PASTS AND FUTURES>>

- *Context*: The past that we see as truth is in fact the particular writing of history: it is a text amenable to [[DECONSTRUCTION][DECONSTRUCTION]].  The futures that we are ‘given’ are, similarly, only some of the ones that are in-principle-possible due to the evolutionary nature of concepts exposed by their [[GENEALOGY][GENEALOGY]].
- *Problem*: The past and future are put to use within discourse, resulting in some winners and some losers.  The results we see may *conflict* with our sense of what we would prefer to have happen.
- *Solution*: We ask: which interpretation of past is valorized?  What histories make the present problematic?  Which vision of the future is used to maintain the present?  Alternatively, which visions undo the unity of the present?

# Example: We can compare the histories of R and Emacs.

*** REORDERING KNOWLEDGE
<<REORDERING KNOWLEDGE>>
- *Context*: Trends and problems are emergent, historical, and political: they are embedded in complex webs of becoming.
- *Problem*: It’s not always obvious how to move /between/ the ‘layers’ mentioned above. This *conflicts* with any given effort to empower oneself with a deeper understanding of the situation.
- *Solution*: We ask: how does the ordering of knowledge differ across civilization, gender and episteme? What or Who is othered? How does it denaturalize current orderings, making them peculiar instead of universal? What tools can we use to reorder knowledge, to make it available in new forms without necessarily requiring the same historical baggage?

# Example: What are the myths and metaphors in the ‘user’ and ‘developer’ communities?  How do users and developers see themselves?  E.g., some perspectives is wrapped up in the concept of “hacker culture” which emerged in a given time and space, with a given relationship to technology.

# Maybe the documentation isn’t written down, but it is in the community
# ... I need to get to know these people and learn from the hackers
# ... cf. Hackers’ Dictionary

** PARs

Before turning to our main application, we will introduce one more
technique — although we will not use it until the end of the paper.

The US Army produced a methodology called the /After Action Review/ or
AAR cite:Training-the-Force.  AARs can be used to assign
responsibility when things ‘go wrong’, and can help people figure out
how to do better next time.  It has been used effectively in business
settings cite:learning-in-the-thick-of-it.

In a more fully collaborative and distributed peer-to-peer setting, we
needed an adaptation of the AAR that made it a more open ended. We
came up with the following template:

1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?

When we fill in the template, we call it a /PAR/.  The acronym has stood
for various things over the years, but we feel it works best a
stand-alone term — with reference to the corresponding concept in
golf, we get a sense of how we’re doing.  Like the Army, we typically
use PARs retrospectively (so, asking, “what /did/ we expect to learn or
make together?”): but they can also be applied to look forward.  In
that case, item #5 might be expanded to include a number of different
scenarios.  Some further things to note:

- PARs are related to patterns, although they don’t necessarily have
  the ‘repeating’ aspect.  Nevertheless, they help us to understand
  context, its problems and proposed solutions.  In this sense they
  might be seen as a template for proto-patterns.

- In our collaborative practice, once when we have collected a
  suitable number of PARs, we can use them as data for analysis with
  CLA. Metaphorically, this ‘integrates’ the ‘tangent vectors’ that we
  spotted when we were working together.

* Application

With the tools from Section [[methods]] at our disposal, we can now turn
to a CLA of the /design patterns community/ (creators, users?).

** Litany: Understanding data, headlines, empirical world (short term change)

Recall that this section is also referred to as the ‘problem’ layer.
The pattern community is not short on problems: a ‘problematizing’
view of reality is one of the main features of the design pattern
method.  However, there are a range of problems that the community is
familiar with which are not fully solved.  For example, ‘Alexander's
Problem’, as described by his collaborator Greg Bryant:

#+begin_quote
# His books are influential, and have inspired countless good acts. But
... despite all of the tools he created, his penetrating research, his
many well-wrought projects, and his excellent writing, he did not
manage to grant, to his readers, the core sensibility that drove the
work. He also did not organize the continuance of the research program
that revolves around this sensibility. cite:bryant2015
#+end_quote
Coming at similar issues from a different direction, Alexander framed
a related query for programmers using pattern methods:
#+begin_quote
What is the Chartres of programming? What task is at a high enough
level to inspire people writing programs, to reach for the stars?
cite:alexander1999a
#+end_quote
These are some of the high-level problems that are known and discussed
in the patterns community, but which do not necessarily have consensus
answers.  More recently, Dawes and Ostwald cite:dawes2017a develop an
elegant taxonomy of existing criticisms of the pattern method.  In
outline, their taxonomy covers criticisms at the following three
layers:

- Conceptualisation :: Ontology, Epistemology \newline /(e.g., “Rejecting pluralistic values confuses subjective and objective phenomena”)/
- Development and documentation :: Reasoning, Testing, Scholarship \newline\hfill /(e.g., “The definitions of ‘patterns’ and ‘forces’ are inexplicit”)/
- Implementation and outcomes :: Controlling, Flawed, Unsuccessful \newline\hfill /(e.g., “Patterns disallow radical solutions”)/

By showing how the criticisms relate to one another, Dawes and Ostwald
begin to develop a [[GENEALOGY][GENEALOGY]] at the level of critical perspectives.[fn::
Let’s check: is this too much a stretch of what Inayatullah/Foucault
said? -JC] In a parallel work they analyse the structure of /A Pattern
Language/ cite:Dawes2018, and develop three alternative perspectives on
/APL/'s contents, which they refer to as the *generalised*, *creator*, and
*user* perspectives.  These perspectives amount to different techniques
for [[REORDERING KNOWLEDGE][REORDERING KNOWLEDGE]].  We will elaborate at the next level.

** System: Systemic approaches and solutions (social system)

At this level, we examine where the familiar problems come from.
Using graph-theoretic measures Dawes and Ostwald cite:Dawes2018 found
that:

- The creator model appears to be /less intelligible/ than the user model, while
- The creator’s perspective of the language is /more beautiful/.

Their central finding, however, is that many patterns in which
Alexander had medium or low confidence in fact occupy a relatively
central position in /APL/'s graph:

#+begin_quote
the patterns which are most likely to be encountered by designers –
are most easily accessed, or provide greatest access to other patterns
– might be those which Alexander acknowledged were incapable of
providing fundamental solutions to the problems they addressed.
#+end_quote

This means that novice users could be expected to encounter problems
in application of /APL/'s patterns: “despite its often authoritative and
dogmatic tone, Alexander’s text was framed as a work in progress,
rather than a definitive design guide” (p. 22).  Dawes and Ostwald
suggest that their analysis could point to “prime opportunities to
continue the development of /A Pattern Language/'' (p. 21).

Here, however, a range of issues more closely linked to software and
media begin to crop up.  There are a range of ‘other’ pattern
discourses which could be relevant here — ‘other’ in the sense
mentioned in our [[REORDERING KNOWLEDGE][REORDERING KNOWLEDGE]] pattern, so not necessarily in
close touch with PLoP — these include PurPLSoc and the world of
practicing architects.  There have been some attempts at creating
systematic archives of patterns, but these have always had significant
buy-in from a wide community.

Importantly, the first-ever Wiki was developed in connection with a
platform for developing, sharing, and revising pattern languages
cite:cunningham2013a.[fn::
http://wiki.c2.com/?PeopleProjectsAndPatterns][fn::
http://c2.com/ppr/] However, there was a distinction between the
discussions and the finished patterns.  In the 2013 retrospective,
Ward Cunningham writes:
#+begin_quote
The original wiki technology functioned in a direct open-source mode,
which allowed individuals to contribute small pieces to incrementally
improve the whole.
#+end_quote
This is true — for some suitable definition of “open source” — but it
could be misleading, in that there was little attention on the c2 wiki
to licensing or collaborative revision of patterns.  Furthermore, when
it came to user rights associated with the ‘finished’ patterns,
discussions were to take place in “letters and replies”[fn::
http://c2.com/ppr/titles.html] — whereas rights in the patterns
themselves were more closely guarded.[fn::
http://c2.com/ppr/about/copyright.html]

Although Wiki technology could in principle have been a site for
ongoing [[DECONSTRUCTION][DECONSTRUCTION]] of patterns, this didn’t seem to happen.  The
fact that this didn’t happen is itself interesting and worth
deconstructing.  Notably, there were only /four/ published “letters and
replies”[fn:: http://c2.com/ppr/letters/index.html].  Unfortunately,
we could not find a public archive of the “design patterns mailing
list” where further discussions took place.

Over the years other issues and concerns came to the fore, notably
Jenifer Tidwell’s charges against the Gang of Four (alongside other
developer-centric pattern languages) resonate with what we saw in
Dawes and Ostwald, above:

#+begin_quote
... the reality of a software artifact that the developer sees is not
the only one that's important.  What about the user's reality?  Why
has that been ignored in all the software patterns work that's been
done?  Isn't the user's experience the ultimate reason for designing a
building or a piece of software?  If that's not taken into account,
how can we say our building -- or our software -- is “good”? — http://www.mit.edu/~jtidwell/gof_are_guilty.html
#+end_quote

# This gets back to the DIVERSITY stuff
# Alexander wanted
# Example of Facebook being designed for ‘end’ users but there are actually many different users and ‘stakeholders’...

Notice that now the /user/ of the designed artefact has entered the
story as a different figure from the “user” of the pattern language
who we met above.  Tidwell’s critique suggests at least a couple [[ALTERNATIVE PASTS AND
 FUTURES][ALTERNATIVE PASTS AND FUTURES]]: e.g., what if the end-user had been
placed at the centre the whole time?  Alternatively, what if the
primary focus of patterns was to facilate interaction between
different stakeholders?  The fact that Tidwell’s book
cite:tidwell2010designing and an essay by Jans Borchers that draws
inspiration from her critique cite:borchers2008pattern both have over
1000 citations on Google Scholar shows that the thinking involved has
been impactful.  To get a sense of how the pattern community has drawn
from this critique and other similar kinds of concerns, we can look at
how the writers workshops at PLoP have evolved over time.  Workshops
did not always have names; where they were named they are included in
this list, even when the names are strictly allusive.  We can see how
the focus evolved from primarily ‘programming’ oriented to a much
broader contextual view over time.

# (Comment here: Noorah’s points about customization as a way into
# free software seem related to Tidwell’s ideas.)

# https://designinginterfaces.com/firstedition/

*1997*
| Architecture               |
| Roles and Analysis         |
| People and Process         |
| Domain Specific Techniques |
| OO Techniques              |
| Non-OO Techniques          |

*1998*
| Agricultural Valleys  |
| Network of Learning   |
| Zen View              |
| Four-Story Limit      |
| Mosaic of Subcultures |
| Site Repair           |
| Scattered Work        |
| Eccentric Nucleus     |

*2000*
| Office Connections      |
| Connection to the Earth |
| Network of Learning     |
| The Unselfconscious     |
| Quiet Backs             |

*2006*
| Small Services Without Red Tape |
| Sleeping in Public              |
| Intimacy Gradient               |
| Connection To The Earth         |
| Thickening The Outer Walls      |

*2007*
| Girl with a Scarf |
| Fu Dog            |
| Sun Singer        |
| Centaur           |

*2008*
| Design & Architecture  |
| Software & People      |
| Processes and Services |
| Security & Quality     |

*2010*
| Frameworks & Environments |
| Process & Design          |
| People & Ideas            |
| Security & Systems        |
| Reliability & Trust       |

*2011*
| Architecture |
| Design       |
| Information  |
| People       |
| Pedagogy     |

*2014*
| Narrow Road to the Deep North |
| Pattern Language and Mining   |
| Testing and Development       |
| Security                      |

*2015*
| Pattern Writing                 |
| Software Architecture & Process |
| Cloud & Security                |
| Innovation & Analysis           |
| People & Education              |

*2016*
| Vikings    |
| Generators |
| Vanguard   |

*2017*
| Roughness                 |
| Simplicity and Inner Calm |
| Local Symmetries          |
| Strong Centers            |
| Not Separateness          |

*2019*
| Group Architecture |
| Culture            |
| Meta               |
| Education          |

\rowcolors{2}{gray!25}{white}
** Worldview: ways of knowing and alternative discourse

The situation with licensing on c2 is particularly interesting in
light of Alexander’s perspective that /APL/ was a “living language”.  In
principle, Wiki technology might have presented the opportunity to
realise this vision fully for the first time, in a virtual setting.
Wiki technology did become widely influential when it was combined
with a free content license on Wikipedia (originally GNU FDL, later
CC-By-SA).

Fast-forwarding to the present day, Christopher Alexander’s website
=patternlanguage.com= writes about [[https://www.patternlanguage.com/membership/memberstour3-struggle.html][The Struggle for People to be Free]] —
but it is not referencing freedom in the Stallman sense.

In 1979 he was concerned: “Instead of being widely shared, the pattern
languages which determine how a town gets made becomes specialized and
private.”  In 2021, /APL/ itself is only legally available for
subscribers or for people who purchase a paper copy of the book. (Or
through a library!)  Of course, like most famous texts it is available
extra-legally for download as a PDF, but this format does not afford
downstream users the opportunity to collaborate on the text’s further
development.

Gabriel and Goldman talk about sharing and ‘gift culture’ in their
essay [[https://dreamsongs.com/MobSoftware.html][Mob Software: The Erotic Life of Code]], and discuss a way of
working that seems to bring back the early days of hacker culture.
(Notably, this essay was presented as a keynote talk at the same
programming conference where Alexander had spoken four years
previously.)  They reference the open source community — but not the
free software community, so we will follow Gabriel and Goldman’s usage
here — as the origin of Mob Software.

#+begin_quote
Because the open source proposition asked the crucial first question,
I include it in what I am calling “mob software,” but mob software
goes way beyond what open source is up to today.
#+end_quote

That crucial first question is:

#+begin_quote
What if what once was scarce is now abundant?
#+end_quote

It is well known that the PLoP conference series is significantly
influenced by Gabriel.  The series features attention not only to
workshops cite:gabriel2002a but also /games/, informal gifts, and
creating a sense of psychological safety: indeed, the central issue of
making a space where ‘failure’ is OK and even celebrated, as per Mob
Software. The essay develops its own criticisms of open source, e.g.,
“the open-source community is extremely conservative” and forking
happens rarely.  (Five years later, with the creation of Git, forking
became considerably more typical.)  Resonating with Tidwell’s critique
from above:

#+begin_quote
One difference between open source and mob software is that open
source topoi are technological while mob software topoi are people
centered.
#+end_quote

On a technical basis, Gabriel’s vision sounds a lot like today’s world
of /microservices/.
# #+begin_quote
# Picture this: All devices that include computing elements are
# connected, and their collective software forms one large
# system. ... Almost all the source code for this massive
# system—estimated in the billions of lines of code—is available under a
# license that grants total recombination rights: Any fragment of source
# code can be used for any purpose.
# #+end_quote
While his vision hasn’t fully come to pass — there are still many
services with proprietary source code — nowadays many big companies
are also big proponents of open source.  Here we can notice that
Gabriel was employing a technique imagining [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND
FUTURES]], e.g., he imagined a future in which:

#+begin_quote
Mentoring circles and other forms of workshop are the mainstay of
software development education. There are hundreds of millions of
programmers.
#+end_quote

We would like to dig somewhat deeper into the foundations of the
worldview that Gabriel puts forth in this essay. Usefully, an article
by VanDrunen “traces the source of Gabriel’s ideas by examining the
authorities he cites and how he uses them and evaluates their validity
on their own terms” cite:vandrunenchristian.  His critique functions
as a (detailed) [[DECONSTRUCTION][DECONSTRUCTION]] of the thinking behind Gabriel’s essay.
Some key excerpts appear in Table [[tabone]].
# [fn:: Maybe these should be organised using
# the same taxonomy of critiques we introduced above.  Also, we
# shouldn’t be totally lazy: maybe there are some things that VanDrunen
# missed: let’s check. -JC]

#+NAME: tabone
#+CAPTION: Key observations from VanDrunen’s critique of Gabriel’s “Mob Software” essay
#+ATTR_LATEX: :environment longtable :align |p{\textwidth}|  :label tabone
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| “Kauffman’s work is about a rediscovery of the sacred, and it amounts to a proposal of the laws of self-organization as a new deity”                                                                                                                  |
| “One thing we find in common with Lewis Thomas’s ants, Kauffman’s autocatalytic sets of proteins, and the agents inhabiting Sugarscape is that they all lack intelligence.”                                                                           |
| “In other words, the rules given by Gabriel describe only the conforming aspect of group behavior. In reality, there is a tension between independent and conforming tendencies, and the flock patterns emerge from the interaction between the two.” |
| “His examples of ‘mob activity’... the making of the Oxford English Dictionary, cathedral-building, and open source software discussed later—all had oversight, master-planning of some sort.”                                                        |
| “There are several distinct senses of ‘gift’ that lie behind these ideas, but common to each of them is the notation that a gift is a thing we do not get by our own efforts.” (quoting Hyde)                                                         |
| “Certainly proprietary code is shared property among those working in a corporate development team, but it is not common to the larger community of software developers and users.”                                                                   |
| “A computer program is not like a poem or a dance in this way; if the programmer is not able to produce something parsable in the programming language or cannot fit the instructions together in a logical way, the program simply will not work.”   |
| “Gabriel’s own experience may color his perception. He founded a software company that produced programs for Lisp development and which went bankrupt after 10 years.”                                                                                |
| “Moreover, if Gabriel means to suggest that these programming languages or models could have made programming more accessible to the masses lacking technical skill, it is quite a dubious claim,”                                                    |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

** Myths: metaphors and narratives (longer term change)

VanDrunen surfaced various concepts in Gabriel’s essay that would be
at home at this level, for example, the concept of duende that Gabriel
takes over from Garcia Lorca originally derives from /dueño de casa/,
the name of a certain kind of household spirit.  VanDrunen’s critique
is also useful for our purposes because it points to the importance of
considering the deeper layers in developing a concept.  It’s not just
a matter of finding a culture’s myths: where may also be a conflict at
this level.

One important narrative for the pattern discourse is in plain view
within the terminology of problems and solutions, which come from
mathematics or physics.  Alexander’s worked /at the level of narrative/
to connect the patterns discoures to a scientific worldview, seeking a
sense of objectivity.  For example, in “The Atoms of Environmental
Structure”:

#+begin_quote
most designers ... say that the environment cannot be right or wrong
in any objective sense but that it can only be judged according to
criteria, or goals, or policies, or values, which have themselves been
arbitrarily chose.  We believe this point of view is mistaken.
#+end_quote

Notice that, here, the discourse is position as different from the
mainstream.  The key differentiator is not the language of problems
and solutions which would be familiar to anyone with an engineering
background; rather, but in a certain notion of /wholeness/.  Which
notion of wholeness remains to be surfaced.  Quoting, again, from “The
Atoms of Environmental Structure”:

#+begin_quote
We believe that all values can be replaced by one basic value:
everything desirable in life can be described in terms of freedom of
people’s underlying tendencies. ... The environment should give free
rein to all tendencies; conflicts between people’s tendencies must be
eliminated.
#+end_quote

Historically, there are at two major varieties of wholeness: one that
is based on progressive differentiation (perhaps understood as
unfolding from substance, per Spinoza), and the other generated
through interaction between components (perhaps via mutually
reflecting monads, per Leibniz).

We can obtain some [[DISTANCE][DISTANCE]] by thinking about how different kinds of
wholeness are associated with different symbols.  Familiar examples
include the circle, the cross — or potentially the cross inside a
circle, \begingroup\alch\symbol{"3B}\endgroup.[fn:: The alchemical symbol for verdigris, and the planetary
symbol for Earth.]  Related but more elaborated symbols include the
circle with a cross rising above it, belonging to the Carthusian order
(/Stat crux dum volvitur orbis/ — The cross is steady while the world
turns) — the Rod of Asclepius (the deity associated with healing or
making whole) — sometimes inter-confused with the Caduceus (the symbol
Hermes, the deity assocated with mediation of various forms).

These symbols are not used explicitly in the patterns discourse,
however we are drawn to them as reference points because it does
appear that the pattern discourse is drawn to /both/ major traditions of
wholeness, and moreover, seeks to unite them.  We get the idea of
unfolding in /APL/ and other pattern languages that work top-down:
however, we also get the notion of patterns and principles that are
/generative/ of emergent phenomena.  As we mentioned above, at this
level, architecture and programming were seen to unite, perhaps
pointing in the direction of bio-hacking and Assemblers, at least at
the allusive level if not at the concrete level.

Relevant to the overall case we are making here, the following
quote suggests we are on a fruitful track:
#+begin_quote
Generative patterns work indirectly; they work on the underlying
structure of a problem (which may not be manifest in the problem)
rather than attacking the problem directly.[fn:: https://wiki.c2.com/?GenerativePattern]
#+end_quote

Clearly, another key metaphor in the discourse is the metaphor of /a language/:

#+begin_quote
... as in the case of natural languages, the pattern language is
generative. It not only tells us the rules of arrangement, but shows
us how to construct arrangements - as many as we want - which satisfy
the rules. (The Timeless Way Of Building, pp. 185-6, quoted at /ibid./)
#+end_quote

Although Alexander’s aims at the glory of God, his writing contains
many traces of symbols asociated with Hermes:

#+begin_quote
In the house, [Hermes’] place is at the door, protecting the
threshold... He could be found around city gates, intersections, state
borders, and tombs (the gateways to the other world).
#+end_quote

At the time when he was actively embraced as a deity, Hermes was
typically paired with Hestia, the goddess of the hearth, whose “domain
was internal, the closed, the fixed, the inward.”  The discourse
around patterns certainly contains aspects a movement “to archaic
roots” present in other 20th Century thought: but unlike some of
these, patterns methods are apparently working to restore “the
dialectic between centripital immobility and centrifugal mutation.”
One aspect of this is a movement towards foundations and Hestia (per
/ANO/).  The resolution within pattern language — as a form — seems to
be along Nietzschean lines: “anything that is becoming returns” (i.e.,
is discussable as pattern), and “contingency resolves itself into
necessity” (i.e., the wholeness of generativity recovers the wholeness
of unfolding).[fn:: See also cite:bishop2020holistic.]

* Discussion

Within our own practices we have combined patterns, PARs, and Causal
Layered Analysis.  Per cite:corneli2015a, we think of patterns as
‘incomplete’ — not simply as pointing to other patterns but as
themselves requiring ongoing work to implement.  We use them as a
project management tool, attempting to maintain surjective mapping
from patterns to Next Steps.  However, this process itself requires
instrumentation.  We try to do PARs frequently, using them both as a
way to maintain a sense of shared mindfulness, and a source of
summaries.  Relevant to the development of our work, they are similar
to tangent vectors: they tell us where and how things are going in the
moment.  Since learning about CLA, we attempt to reanalyse the data
generated in PARs on a regular basis.  This leads to an evolving
answer to the question “what is our vision for change and how is
progress measurable?”  Specifically, progress becomes measurable
through a set of forward-looking TODO items that operationalise the
vision.  These disparate TODO are then given a more coherent existence
by associating them as Next Steps to our patterns, or creating new
patterns as appropriate.

We think that this tripartite workflow of /reflection/, /integration/, and
/operationalisation/ will be useful in many other settings.  These steps
are mutually supportive.  Without one or more of them, we run the risk
of missing something important.  These cycles may be useful for
individual or overlapping communities, but it certainly remains to be
seen whether they could be extended across the entire pattern
discourse in its full transdisciplinary extent.

Relative to the analysis, above, here are high-level TODO items
collected from across the layers above, which we might suggest need
further attention:

- Litany :: Develop a pattern language of critiques and flaws of the pattern method, elaborating the criticisms of Dawes and Ostwald and showing how and where these criticisms can be usefully applied, or where they are out of scope.
- System :: Develop a pattern language of PLoP, more thoroughly reconstructing the thematic and historical development of the research to date and elaborating its next steps.
- Worldview :: Develop a pattern language of the philosophical and spiritual commitments held by practitioners.
- Myth :: Develop a catalogue of significant symbols used by practitioners and how they relate to long-term historical developments.

(Note that it is strictly not necessary to develop a “Key to All Mythologies” in the sense of Edward Casaubon from Eliot’s /Middlemarch/!)

* Conclusion
*1. Review the intention: what do we expect to learn or make together?*
- Our intention was to apply the CLA method from future studies to the pattern theory, and to use it to answer the core question: “what is our vision for change and how is progress measurable?”
*2. Establish what is happening: what and how are we learning?*
- Walked through the CLA’s layers, using the Poststructural Futures Toolbox to help surface connections and ideas, drawing on empirical, interpretive and critical perspectives.
*3. What are some different perspectives on what’s happening?*
- JC: I did most of the hands-on-the-keyboard writing this time, aided by frequent and detailed discussions with Ray, and an editorial perspective added by Charlie.
-
-
*4. What did we learn or change?*
- Relative to our earlier work where we attempted to use present patterns to the futures community, this seems much more mature.  It is a fitting third installation in Joe’s “Patterns” trilogy.
-
-
*5. What else should we change going forward?*
- We will have to see whether PLoP accepts any of our proposals!
-
-

* Discussion                                                      :noexport:

# To recapitulate our progress so far, we have Surface: Patterns have lots of problems.
# - SYSTEMS: What re the (social) causes  for how we got here? — Architecture by collaborative design, Programs
# - Worldview: "Mob software" — lots of openness, lots of collaboration, critique from a Christian perspective
# - poetic vs prose — way of describing deepr realities - inyatullah says to get to myth layer you need a poet

- Where do the patterns come from?
- Where do the problems come from?
- Maybe patterns /work at the surface layer/ and miss the depth.  Patterns are often aimed at solving a problem where we assume that the context is given.  But what if the conflict is at the lower layer, not seeing eye to eye.
- What we need to do is harmonize the worldviews not dance around it.

- Alex: it’s like writing the same program with the same HLL
- If you had a couple that ultimately realise that there is a disagreement between /quality of ingredients/ and /self-reliance/.
- Alex: Would an emotional argument be a case of 2 people trying to get to this level?
  - RSP: Getting towards metaphors and myths, this is the kind of thing that people invest a lot of energy into.

- ‘Elevator space’ vs ‘elevator talk’

#+begin_quote
A quote from the paper on Alexander's battle for beauty: "a book published by Oxford University Press, the epitome of oak-paneled academic respectability"

And a quote of Alexander from TNO by way of the same paper : "MAY BE BEST IF WE REDEFINE THE CONCEPT OF GOD IN A WAY THAT IS MORE DIRECTLY LINKED TO THE CONCEPT OF ‘THE WHOLE.’" Sounds like Spinoza!

Here's a fine elaboration of the dictum from the beginning of ch. 2 of SoF: "It is based on the idea that every design problem begins with an effort to achieve fitness between two entities: the form and its context. The form is the solution to the problem; the context defines the problem. In other words, when we speak of design, the real object of discussion os not the form alone, but the ensemble consisting of the form and its context. Good FIT is a desired property of this ensemble which relates to some particular division of the ensemble into form and context."

A page or so later, he adds: "Indeed, in the great majority of cases, it is necessary for the designer to consider SEVERAL DIFFERENT DIVISIONS of an ensemble, superimposed, at the same time." (!)
#+end_quote

- Or with a doctor and the rod and snake, we can achieve this kind of wholeness
- Joseph Campbell is the hidden link between STAR WARS, 2001, MAD MAX

- PLoP can consider: “we own levels 5 through infinity!”

- ‘Rescue of Leia consistent with male rescuing female.’
- “you don’t need to be good at mathematics because you’re a girl”
- Now math can be used to guess the gender of the programmer!
- Remind them of Ada Lovelace Byron!
- Having all these things where that’s the way the story goes, what about changing the gender roles.

- How did myth get a bad wrap?  Because it’s where ingrained prejudices can stay ingrained.
- What if our relationship to myth and mathematics were the same — ongoing discovery and invention.

- E.g., with STAR WARS there was a bunch of technical stuff in reality (going to the moon), but then there was the symbolic structure keeping up with each other.  In a more collaborative culture, it wouldn’t have been a race but a collaboration.  STAR TREK: space is so interesting that it, itself, has brought peace between the nations.

- but of course it goes both ways where you get the symbolic stuff anticipating technical progress.
- We could try to investigate the symbolic precursors of this... — maybe someone else has done this (e.g., stolen serendipity from Bacon)


- Living on a reservation, with someone else's mine on it, they are called a country but they are not, it's an ambiguous place sort of recognised as a nation but not completely; Indian Officer saying who's in the community and who's not.

- Old patterns don't work anymore — in the old days trash was left over organic food remains.

- ‘Wholeness’ as another key metaphor
- There’s something curious going on here, though, relative to another key concept for pattern theory, namely, the concept of wholeness.


The myths could have to do with how aligned we are with the world.
- Inayatulah might have a hand-off to a therapist and say it's at the level of the body...?

- If they are very distant or different then there's lots of conflict
- Planes allow infinite number of choices so you have S^1
   - Metaphorically, out of all the possibilities I choose only two dimensions to look along.

- On these two, you could do a conceptual blend of X and Y - these two seem to be the most two relevant dimensions for now.
   - But what if you have to consider multiple concerns, e.g. - speed, environment, and health
    - if I can get all three to balance we can cut down the complexity on the way there by taking them 2 at a time.
    - There are boundaries to the usable region inside the space.  If I try going too far it becomes unhealthy to me and to the environment.
   - This re-explores the context and its possibilities in a creative way.

- Possibly recall our metaphor of the ellipse and fleshing it out a bit

- Example of multiple worldviews:
   - We have at least a constant (bigger than the distance between the points)
   - and plane to chose after we nominate the context and community — what might
   - these represent.

- Context = Community : case of a circle
   - The radius could represent something, even if the points are 'close', there may be a big or a small radius
   - How aligned are the community and the context?
   - Colonial representation, even a sympathetic one, might not be aligned with our needs.
  - How do we get along with people who have different worldviews?
- Recognise them and find out what they are!
  - Maybe it's actually your projection of the noble savage on someone who didn't match that
  - Boyle and Spinoza: did have seem to have humongous disagreements. They had Oldenberg in the middle to keep them from tearing each other apart, and leave things silent.
  - It's a different kind of conflict if they are in communication vs if the myths are left unconscious (not in communication with each other).  So, here are some techniques to bring things out.


- Leo: RGCS: open-communities with another stance?
- Ray, we could mount a similar critique for PLoP, Free software, Futures... they aren’t being singled out.
- Joe: this is part of the /context/ even if we don’t explicitly talk about it.  There are multiple ways of splitting something into a context, and a good designer should consider the splits.

- We need to rethink what we were doing with patterns.
  - THIS IS NOT JUST FOR PLoP but also for peeragogy, cf. the clash of Prometheus & Themis.
  - We have a Promethian myth of open source, but there’s also /concern for the common person/.
    - Going back to what we were talking about with thinking about peeragogy using open source tools and the back-reactions we received
- MAYBE WE HAVE SOMETHING to add to the futures community as well!
- There may be some problems with problem/solution/context if I didn’t fully understand my community
- E.g., with the patterns for a carbon world could see a mismatch between patterns for a car-free world unless we understand cars as a symbol of a core American value.
- So we may need to accept we won’t have a car-free world, but we need to run the car on a different fuel.

# - Walking in 2 different directions through familiar territory
# - rekindling a sense of humility!
# - E.g., fomenting ability to INTERRUPT
** Next steps

- NNexus + recommender for learning
- Point out that this applies to synthesis later on
 - Would be useful to have

- What does change at the myth level look like?
- The ship that came in 1619 was actually a pirate ship, they happened to find slaves rather than gold...
  - Remarkable...!
  - It went back to the particular pirate ship but once it got started, then you started to invent myths, "the South"
  - 400 years later, you have /controversy over the statues/.
  - We don’t use ‘Altavista’ any more but we still know what it is, you can’t get rid of the symbol

- ‘Patterns’ are more at the immediate level
- Nevertheless, the patterns may embodying a worldview (e.g., at least the worldview of design) — rather than the deep

- Needing to build schools, user interfaces, etc.
- Comment about silos: how *interoperable* are the patterns?
  - I don’t care to be rewriting the whole thing
  - I need some math, come to our next session... no I just want to explain these (familiar critique in the peeragogy project)
    - But now we got a bunch of newcomers saying we want to write a 5 page intro
    - This could get back to conceptual blend
    - ‘Peeragogy and Handbook’
    - ‘Wikipedia’ is a wiki and an encyclopedia; then you get WikiData...
- In this ghetto we do Alexander patterns, here we do 15 principles, here it’s Takashi...
- Which are the problems that are /invisible/ (the fish doesn’t see the water it is swimming in)
  - They think of their own freedom but not that of the other people’s priorities
- E.g., you’re supposed to go in person to join the Workshop...

- Rejecting pluralistic values, and others...
- Cf. our annotated bibliography in Google Drive

We aim to surface answers to some of the questions and concerns raised
in the introduction.

- One of our challenges with the Futures paper was that they were not well-versed in patterns
- That problem doesn’t exist if we are submitting to PLoP, but we have the opposite problem
- So, keep it light with CLA — with our previous paper, it was trying to push the Futures and Patterns literature at the same time

- What if I’ve built things at this level, but I haven’t dealt with this.
- Then maybe you have a dominance of rosy glasses problems-and-solutions
  - Does this then mean “oh we just need new patterns?”
  - The mythos is intact even though you changed the surface
  - “dominant group” persists; ‘divine right of kings’ or the mythos of the caste system; feet of the original humans
  - Patterns and anti-patterns (and CLA) of communism would be an interesting sequel
  - Bolsheviks had the /idea of a professional revolutionary/.

** Callback to design as blending in the previous paper
** Callback where relevant to peer learning and peer production in the first paper
** Other notes

In a way, the need for a ‘complexity of wholes’ should not be
surprising in light of current perspectives from neuroscience
cite:mcgilchrist2019master.  (NB I think there was someone who showed
up at Cicolab a while ago who had written a paper on patterns and
systems or patterns and complexity theory.)

- Go in, /patterns/ don’t need to be defined; we can make a nice clean reference to our PLoP paper
- Do people only recognise myths until they encounter different cultures?
- It’s /dynamic/ moreso than /robust/ or /resilient/ — behind the terms, you might find that adaptive capacity is compatible
 - Branching processes; 1 customer tells 2 of their friends.
 - Is the growth-rate bigger than the death rate?  If so it will grow until whatever carrying capacity.
 - We need social distances on youtube...
 - Survival analysis in Tim’s thesis?
- It’s not just the meme going viral, it’s also spawning whole discourses
 - it can’t just branch forever, it will run into new limitations; and what is the individual?
 - what if these interact so much that it becomes the new individual?
  - This is how we spread the new myth, but it then dominates
  - E.g., with the pattern community, this isn’t too much /unlike/ Alexander’s dynamics that Ray’s been reading about in /Synthesis of Form/
  - E.g., I don’t always control things — this is evolution not intelligent design.  I’m a co-creator!  The dao will be flowing, but I may be able to skillfully move things around and work with it.  This doesn’t negate design patterns, I just need to understand their scope.  In a very simple case of design, these are materials I can master them.
  - E.g., I made the design with plastic, vs natural stone with weakness points... you’re also engaging with an outside world
- Solutions, problems, and context — the context may be active and dynamic!
- We were talking about Alexander and the design of a rocket.  Getting to the moon is difficult, we have 2 big moving bodies nearby.  I need to plot a trajectory in this context; it’s not as simple as shooting as a moving target; there’s a lot going on... this could lead to all kinds of counterintuitive things.
- Analua was talking about /deep resiliance/ — would this relate to the /adaptive capacity/ stuff


# ‘Participatory nature’ + there may be users
# ‘Patterns existing at the litany level’ is worthy of the pattern
# Burn books, make up stories of the past — vs — empowering the citizens (making your own myths)

# today more and more design problems are reaching insoluble levels of complexity... a background... specialist information, widespread, disorganized... specialists... never best clear — This is definitely

# Traditional builder knew about alcoves — and you learned the
# patterns, you didn’t need to write them down (cf. PNG culture as a
# boundary case).

# nowadays we have new kinds of materials... we now need to think it w/
# modern materials

# “IKEA effect” people actually like them because they put things together

# Problems were so rare that there were not actual designers!

# Down to the level of “brass tacks”

# Copy had to be exact — personal intuition — emphasis on intuition
# 2 hemispheres, 2 cultures
# — logic and geometry vs intuition

# In a well-functioning there are interconnections between brain centres
# (and turn each other off, selectively; the society of mind isn’t having a civil!)

# So, remind people what Alexander said at the beginning
# — cf. the critiques of patterns taxonomy — almost like the LITANY CONCEPT
# — have others mentioned things about ‘open source’?

- Feminism (white women) and anti-racism (black men); neither is actively harmed.
- Deeper layer: we /deal with causes/ (in two senses) rather than /humanity/ in general.
  - MLK vs ‘I am a man’ signs (just because I carry garbage)
  - Can relate to wholeness
  - People tend to think about humanity in terms of the particulars of their culture.
  - You don’t want to get rid of a ‘bias by race’ and then find some other group is at the bottom!!!
  - The real solution may involve revising myths (e.g., Horatio Alger)
  - Mulitple literacies (like the ROSETTA STONE as a symbol in the Jung sense of a symbol)
  - Thoth emerald tablet
- We could have lived in an alternative history in which pantheism was dominant
- Isis cults even in London (and maybe Oxford)
  - Maybe it would be a ‘dominant-nondominance’: we want a more pluralistic time, with a variety of different cults.
  - Joseph could have invented Freud’s theory and we might have had ‘dream cults’

** Further
- What is your context? Maybe deepening your context?
** Myth outtakes

- Basic structure of BEGINNING, MIDDLE, END
- The public subconsciously looks for this to hold on to; it’s not just a collection of images but a succession of 3 /narratives/.
- You can only understand a foreigner when you’ve been one.

- ‘are you sure your mob model will work where you claim it from’
  - Adam Smith, invisible hand is an example of invisible hand
- “Theological-Political Treatise” might say something about Spinoza’s philosophy
  - Milton learned about Spinoza from Oldenberg — when this was emerging
    - He was actually getting only ancient philosophy
  - Compare now with Gowers boycotting Elesevier — now we have the Arxiv
    - Ginsparg as analogue to Oldenberg
  - Generation does include the falling away of the gold
- PLoP could find it a bit threatening b/c you have to pay $500 to even have a look at the gate
  - Have you missed the deeper levels?  4 GATES?  84000 gates?  All the same height?
  - ‘Patterns of dissemination of scientific?’
  - After all this practice building PLoP patterns, could we build patterns that are relevant for science, mathematics?

- — How is this relevant to them?

- It’s not that there’s a single way of splitting a context even with kettles
- Consider an ensemble of the kettle ... there seems to be a clear boundary. But I can make changes on the boundary, if it’s the wrong way to heat domestic water... Or it’s not the kettle.

A few pages later, Alexander put a key statement in italic font:
“What does make design a problem in real world cases is that we are
trying to make a diagram for forces whose field we do not
understand. Understanding the field of the context and inventing a
form to fit it are really two aspects of the same process.” To me,
this sounds like where CLA as a methodology could help in the
diagramming. (On the page before it’s all about iron filings as an
example.)

- /The City is not a Tree/ — the designer’s view
- It wasn’t design this way — this is the organic lifelike quality
- Look at things like this that weren’t designed, but make it closer to things like this like how they actually evolve
- It’s not all the way to the forest, but still different from something that doesn’t have any life in it
- Cf. debate between evolution and intelligent design
- Also, PLoP is not a tree — let’s look how it’s developed

- /QFT/ with a vacuum comes close to Spinoza’s physics; Einstein was also a Spinoza fan.
- Cf. the critique of KAKU — which was a critique of HIS VISION OF THE FUTURE
- There’s Spinozist school at the bottom of QFT, but there’s also the ‘shut up and calculate’ school.
  - This must be parallel to the physicist’s view ... a lot of this is similarly narrow
  - Ray: I disagree with string theorists, the main problem w/ QM and gravity
     - You can’t have measurement without the observer effect
     - GR is also defined relative an observer
     - We can’t find both going on in a physical theory!  BUT “if I just take the equations of general relativity... I run into 2 problems, things get anomalous”... if I put in supersymmetry I get past the conceptual problems.  This is interesting math, but as a physicist it doesn’t tell me anything.
     - All the patches without understanding what the program actually does!
- Maybe there are good reasons to stop computing and to start thinking about what’s the nature of the computer

At this level, we connect with the cultural themes that support the
worldview discussed above.[fn:: Incidentally, in the
metaphor /for CLA/ preferred by futurist Rebecca Ryan, we have descended
through the /sunlight/, /twilight/, and /midnight/ zones: we now come to the
/abyss/.  Our explorations here will afford us a view from 20000 feet
/below/ the surface.  We are likely to find some things that appear
strange!]

VanDrunen surfaced many concepts from Gabriel that would fit at this
layer: /faith/, /duende/, /spirits/; more centrally he raises a question,
when encountering different worldviews and myths: are they compatible
with my own worldviews and myths?  Myth also comes up in “Synthesis of
Form” — descriptions of the house are woven into myths at the root of
culture.  “Constant repetition”.

- Now maybe critiques that say “modern architecture is soulless” may be because modern architects are only working at the upper levels of CLA.  Maybe that’s what the quality that Alexander is bringing in!
  - Hypothesis: that in older cultures the 4 levels of CLA were in better contact?
  - ... e.g. because things adapted slowly.
- Where does the synthesis of form take place?  In a context for sure.
- One of his goals was to make something more like old organic architecture; at that time, things were well-integrated with it.
- 20-30 pages to read this week

- Maybe we need to have a religious
- Alda could be interesting for Nigel — Nigel is paying for AIDAN to be set up so he’d likely be interesting.

Furthermore, Leitner cite:leitner2015a does something similar,
mentioning the perception of line (cf. Greg Bryant’s criticism),
referencing Tielhard de Chardin (p. 57), other folks who square their
devout.  Let’s not assume that there’s only /one/ Christian analysis.
Vishudi Magda; [[https://en.wikipedia.org/wiki/Taj_Mahal][Taj Majhal]] isn’t just a religious symbol, it’s also a
symbol of all of India; but also it represents artistic beliefs,
economic wealth (and disparities); and arts patronage.  This touches
on /community/ as well, as a sensed space.  Since we’ve seen this as an
intersection we added it to our definition.

Leitner’s name for what Alexander left nameless is ‘perception of quality of life’.

- Even have things like the car in relationship to the horse!
- Not just the Mustang... now cars and motorcycles have inherited that
- “Iron Horse” is the name of a locomotive
- “The end of the road” — analysis of car culture.  America embraced the automobile like no other.  Should replace the eagle.  America created burbs & covered nation with asphalt.  Changed the whole mindset of Americans...”
- T junctions.  Future of transport.  Now we have the metaphor of the information superhighway; next up is the Internet of Things or even roadsystem of things.  Now instead of people having their own car, we’ll have vehicles delivering things.  You’d need whole different myths.  Compare “The Machine Stops” where people were just living underground.  This would fit with living underground of course — but this runs against the grain of the culture.

- So, OK, if we want to understand how to move to a post-carbon world, look at how they moved to the current carbon-friendly world.
- Or look at pre-linguistic to linguistic, or thinking you could ignore the cultural levels
 - E.g., “Well if we just changed the time of day when people did business...” — so there are lots of patterns of how to do this.
 - How new design patterns can enable cities to change... — OK here’s why we need patterns rather than doing things /ad hoc/. E.g., here’s why we need pattern thinking (patterns for footpaths).  Some places shift things to night time.  Soon though you will get to questions of how the culture operates.  What about cultural assocations of daytime and nighttime?

However, if we go to the central concepts:

- /Context/ /problem/ /solution/...
  - Concept of problem and solution comes from mathematics or physics
  - They are a part of geometry!  Alexander was thinking mathematically.
    - What would be a “pattern language of programs” it would be something that you could use to synthesise a program.
- /Community/ was implicitly there
  - Stakeholders, that was a community.  You’d be missing the nose if you saw a village and not a community.
  - The idea that it’s not just a pattern but a /pattern language/.
  - I think that we should be surprised if it’s /not/ a secular church!
  - There’s some tension between “sacred spaces” and the “sacralisation of space”
    - You’re not going to design everything from the ground up in general
    - You would wreck things if you weren’t to respect the history
    - This includes changes over long term or over many person-hours

- 1500 Boromini :: He put an ellipse in a dome.  Around the same time
  that Kepler found the ellipse in the heavens.  “As above, so even
  more above.” — If we were making an ascent rather than descent.
- *Gates* :: key points

To recapitulate some of the ideas from above: an idea that we gather
from the references to Kauffman point in the direction of the concept
of emergence:
#+begin_quote
An emergent behavior or emergent property can appear when a number of
simple entities (agents) operate in an environment, forming more
complex behaviors as a collective. — /Wikipedia/
#+end_quote

Combinations of patterns coming together to /create/ complexity is
related the idea of emergence.  Let’s have another look at Alexander’s
lecture on “The origins of pattern theory: the future of the theory,
and the generation of a living world”, presented at OOPSLA and
published in /IEEE Software/.  This lecture provides an important nexus
between the world of architectural and software patterns.  In fact, he
posits [[ALTERNATIVE PASTS AND FUTURES][ALTERNATIVE PASTS AND FUTURES]] in which the separation between
these domains dissolves.  What remains are /generative patterns/.  (We
will say more about this below.)

- ‘The computer playing Go can be solved methodically: it can be
  proved into a selection problem.’

#+begin_quote
With further application of the method, futures discourses could
become more ‘generative’, i.e., refashioned as “a kit of parts …
together with rules for combining them” (Alexander, 1968).  To meet
this need, the set of patterns would have to be more fully
elaborated. In the domain of the built environment, Alexander (1999)
refers to inspiration coming from “generative schemes that exist in
traditional cultures” with “as few as a half a dozen steps, or as many
as 20 or 50.” It is not simply a matter of adding more patterns — but
one of understanding the unfolding processes that they represent, when
taken together.
#+end_quote

There’s something curious going on here, though, relative to another
key concept for pattern theory, namely, the concept of /wholeness/.  Is
there such a thing as wholeness that emerges from parts — in the sense
mentioned above — or does wholeness exist prior to the parts?  This
gets into a deeper philosophical debate.

- The question of “what is the Chartres” is different from “What is the Marseilles”?
  - Marseilles does have a cathedral, located in the old port — it’s part of the port
    - There’s also their Notre Dame... but again this is viewed in the context of the port
  - Whereas within Chartres the first thing you think of is their catherdral
  - What if the Chartres of patterns is just regular old Tarot cards which have been around for a long time!

- But asking people about this might be a chalk and cheese question.  Iron next to flowers...

- Redo the /context/, /community/, /conflict/, /problem/, /solution/ stuff.
- Maybe we’re so used to these things that we forget they are actually symbols.

Notwithstanding that some symbols may be ‘hidden’, it makes sense to
have a look at the more overt symbols and
metaphors. https://hillside.net/conferences/plop-conference-proceedings

Architecture
Roles and Analysis
People and Process
Domain Specific Techniques
OO Techniques
Non-OO Techniques

[[DISTANCE][DISTANCE]]: actually we are seeing some of these things taking shape?

*** Social and ethical issues in computing
Even if we disagree with what Gabriel says, the way he says it is interesting!

One paper we read as a class was entitled “How Computer Systems Embody
Values” (Nissenbaum, 2001).

#+begin_quote
I believe, however, that we do see values and beliefs reflected in the
way we program and what we program, but that the reflection comes only
in subtle ways, aspects like the purpose and motivation for the
software and the human interaction around the development of the
software, much more so than the design or coding itself.
#+end_quote

*** Order
Gabriel uses this assumption to disdain authority and any deliberate organization.
*** Gender
Margolis and Fisher, likewise, describe the “person in love with
computers, myopically focused on them to the neglect of all else,
living and breathing the world of computing,” (Margolis and Fisher,
2002, pg 65). The image of such people, they say, turns many people,
especially women, away from the field of computing.
*** God, creativity
- Weizenbaum explains, The computer programmer, however, is a creator of universes for which he alone is the lawgiver.
- it is founded on a presupposition that God is not the orderer of the universe
*** Flocks, sheep, shepherds
This is interesting in light of an observation by Rich Hickey, about
/aggregates/:
#+begin_src
Partial information

+ when requiring / providing aggregates
+ aggregate
  from ad- "to" + gregare "flock / herd"
+ information that travels together
#+end_src
*** Code gardens
What is programming? Is it a leisure activity, like gardening... etc.
*** Programming decontextualised

This is an important admission:

#+begin_quote
In fact, more specifically than that, we are concerned with the task
of programming or coding, which is only one step in the software
development process (other activities include specification, design,
documentation, testing, and maintenance).
#+end_quote

*** Hacker lifestyle
In fact, the “way of hacking you like” (Gabriel, 2000, pg 1) with
which Gabriel tantalizes his audience embodies the very stereotype
that keeps the masses away.
*** Alexander cathedrals
Christopher Alexander’s
denial that “some great architect created these buildings,
*** Does Gabriel’s critique of FLOSS apply to the pattern community itself
“small core teams led by module owners who are strict gatekeepers”
*** End user modifications
“No one would mistake the modifications I have made to my home for
something done by a professional.”

That’s interesting... maybe this is because software itself isn’t a
very plastic medium.  But we have the syntax of the software and the
idea of a computer and these are very different things.

*** Software vs architecture
The reality of software is not inherently embedded in space. Hence it has no ready
geometric representation
*** Practice
My practice was to learn algorithms by coding them.
*** Convergent/Divergent

Mob-software projects tend to be divergent

Perhaps a better example of the work of the mob in computing technology, in Gabriel’s
view, is the variety of uses (and users) of the World Wide Web.

*** The hacker ethic

- We seem to have a contradiction between the individually important
  architect and “the mob” (resonating with Tidwell’s concerns for
  end-users).

*** The mob
Mob software is produced by an aggregate effort of programmers
who are “not individually important”

The rise of the software industry, however, killed the nascent mob software approach.

*** Master planning
#+begin_quote
Software development methodologies evolved under this regime along
with a mythical belief in master planning.
#+end_quote
*** Software

Importantly, Gabriel’s lecture can be seen as the response of the
software community.  It took place the next year in front of the same
body.[fn:: fact check]  It imagines similar outcomes.

#+begin_quote
Early computing practices evolved under the assumption that the only
uses for computers were military, scientific, and engineering
computation—along with a small need for building tools to support such
activities.
#+end_quote

JC: That could be related to the history in /Tools for Thought/ of the
‘radicals’ at all phases who were eager to understand how their minds
work.  VanDrunen says that

#+begin_quote
It was engineering and science types, as opposed to, for example,
artists, who defined how software production was done and understood.
#+end_quote

But this is not what Rheingold’s history confirms: Rheingold tells a
history of the basically psychedelic nature of computing, one in which
the key figures are social renegades and polymaths who may as well be
artists.

*** Duende

The concept of duende is difficult to pin down. It is a
personification of a kind of spirit of artistic
spontaneity. Etymologically, it comes from duen de casa, “master of
the house.”

The duende is a demonic earth spirit who helps the artist see the
limitations of intelligence

JC: So it sounds rather like the clown in cite:handelman1998a.

[I]f you take the fear of humiliation. . . and you try to trace it, you realize that you
have a whole series of linkages in your mind which ultimately go back to the fear of
death. For example, if you are mocked you may lose your job, and if you lose your
job perhaps you will end up in the gutter. . . (Grabow, 1983, pg 86)

The mythology of the rich in the overproducing nations that the poor
are in on some secret about satisfaction ... [has] a basis, for people
who live in voluntary poverty or are not capital-intensive do have
more ready access to erotic forms of exchange that are neither
exhausting nor exhaustible and whose use assures their plenty

*** Scarcity
An important aspect of this Gabriel’s critique is that that it is not
just a matter of getting access to source code that creates a
condition of “freedom”.  As VanDrunen put it:

- “The meaning is, what if there were more people with significant skill in developing software? How would that change how software is developed and distributed and to what uses software is put?”

This is developed in more recent thinking by R. M. Unger.

*** Gift culture
The specific cultural understanding of how ‘gifts’ are meant to be
used and consumed might cast some light on the otherwise confusing
preference for open access at PLoP.  But perhaps more fundamental is
the notion of an /object/.


- “Hyde contrasts the spirits of gift and commodity economies with the Greek words eros and logos. In his mind, eros stand for imagination, logos for logic; eros for synthesis, logos for analysis or dialectic; eros for bonding (including the bonding of people in a relationship), logos for differentiating into parts.”

# DECONSTRUCTION, GENEALOGY, DISTANCE, ALTERNATIVE PASTS AND FUTURES, REORDERING KNOWLEDGE

* Abstract                                                         :noexport:

- Inayatullah has two-page introduction — Ray will be sending
- Was there anything else?
  - Alex: I remember the first time you mentioned CLA to me, I was completely confounded by it.
  - Today I’m starting to know it and understand it as well, based on the examples.
- Finer details felt like a good intro
- Emacs for peeragogues, Peeragogy for Emacs people.
- Maybe next Wednesday meet up at ‘The Punter’
- Let’s write a paper about futures for PLoP and make futures relevant for PLoP and vice versa...

/“What is PLoP’s vision for change and how is progress measurable?”/

- Marnita — has her round table and she brings everyone up to this table
- How do things flow from your mission statement?
- Then you find people with overlapping visions to give.
- Rather than “Free software could be relevant PLoP...”
- Aha, but also “PLoP could be relevant to Free Software...”
  - — but this isn’t going to go very far unless you have a license

- Otherwise you wind up like Spinoza... sure you can publish (posthumously)
- Is it a port city or is it a cathedral city?
 - If you’re going to write about education (not related to programs) why do you need it here?
 - It looks heterogeneous as a litany but maybe there’s a consistent layer?

- /Glass Bead Game/ - is this relevant
- Why can a physicist and an MD talk?  What about the same physicist and a literature scholar?
  - It involves thinking in terms of fundamentals
- This points us in the direction of transdiscplinary design.
* The end                                                           :ignore:

#+begin_export latex
\bibliographystyle{unsrt}
\bibliography{./main}
#+end_export

- AI making AI
- Human intelligence is and can only be embodied
- Karl Friston in Wired
- /AI Ethics/
- NudgeStock — behavioural science
 - Skittles is different colors
 - E.g. Headspace - a lot of users were coming w/ no knowledge... this wasn’t keeping people coming back. — in the first interaction they come away knowing what ...
 - There are some basic principles here
 - Biases are a good starting point (scarcity)
  - Fundraise, audio version, RELATIVE VALUE
  - Compared to other things
- Maybe more about the emotional experience!
- WE ONLY REMEMBER FEELINGS
  - Why would they be wanting to share?
  - "I’m the kind of person who XX?" (status)
  - What are the little things you can do?
- Mailchimp... when people send their first email... you’re so nervous to press send!
  - The screen comes up w/ a celebration animation — to see people celebrate, it’s a feeling not a logical thought process
- How do we explore a process? How do we do things... Info articles, Sophia — travel
- Booking travel — you might not know what you want but you know how you want to feel.
- Lunchclub that’s actually an everything club
  - Practical applications, and never meetings
